"""Guion de LA GUERRA FRÍA — versión entretenida, español neutral.

Reglas fijas del proyecto:
- Español neutral: nunca "vos", "pibe", "che" ni modismos argentinos.
- Cada escena tiene su propio dibujo (clave 'key' -> /mnt/documents/ref_gf/<key>.png).
- Tono entretenido: frases cortas, ganchos, preguntas, datos sorprendentes.
- 'prompt' describe el dibujo de esa escena para generarlo.
"""

def _e(txt, t1, t2, key, prompt, gap=0.5):
    return dict(txt=txt, gap=gap, img=None, t1=t1, t2=t2, key=key, prompt=prompt)


GUION = [
    _e("Imagina una guerra en la que los dos ejércitos más grandes de la historia nunca se dispararon un solo tiro.",
       ["LA GUERRA FRÍA"], ["LA HISTORIA COMPLETA"], "g001",
       "two giant soldiers, one American one Soviet, facing each other with rifles lowered, tense standoff"),
    _e("Duró cuarenta y cinco años, partió el mundo en dos mitades y tres veces estuvo a punto de terminar con todo.",
       ["45 AÑOS"], ["EL MUNDO EN DOS"], "g002",
       "a globe cracked down the middle into two halves, one half shaded dark, one light"),
    _e("Y todo empezó, curiosamente, entre aliados que estaban ganando la misma guerra.",
       ["EMPEZÓ ENTRE", "ALIADOS"], ["1945"], "g003",
       "three wartime leaders seated together at a conference table, smiling stiffly"),
    _e("Mil novecientos cuarenta y cinco. Europa es un montón de escombros humeantes.",
       ["1945"], ["EUROPA EN RUINAS"], "g004",
       "a bombed European city street in ruins, broken buildings, thin smoke"),
    _e("Sesenta millones de personas habían muerto. Ciudades enteras dejaron de existir.",
       ["60 MILLONES"], ["DE MUERTOS"], "g005",
       "endless rows of simple grave crosses fading into the horizon"),
    _e("Solo dos países salen de ahí realmente fuertes: Estados Unidos y la Unión Soviética.",
       ["DOS GANADORES"], ["EE.UU. Y LA URSS"], "g006",
       "two enormous flags, stars and stripes and hammer and sickle, rising above rubble"),
    _e("Uno creía en el capitalismo y en las elecciones. El otro, en el comunismo y en el partido único.",
       ["DOS IDEAS"], ["IMPOSIBLES DE MEZCLAR"], "g007",
       "a factory owner with a coin on one side and a worker with a red banner on the other"),
    _e("No era solo política. Cada uno pensaba que el otro era un peligro para el planeta entero.",
       ["NO ERA SOLO", "POLÍTICA"], ["ERA MIEDO"], "g008",
       "two men pointing accusing fingers at each other across a small globe"),
    _e("En febrero, los tres grandes se reúnen en Yalta para repartir lo que quedaba de Europa.",
       ["YALTA"], ["EL REPARTO"], "g009",
       "Roosevelt, Churchill and Stalin seated for a photograph at a seaside palace"),
    _e("Sobre un mapa, con lápiz, deciden el destino de millones de personas que nunca los votaron.",
       ["UN MAPA"], ["Y UN LÁPIZ"], "g010",
       "hands drawing thick pencil lines across a map of Europe"),
    _e("Stalin promete elecciones libres en Europa del Este. Spoiler: no las hubo.",
       ["\"ELECCIONES", "LIBRES\""], ["NUNCA LLEGARON"], "g011",
       "an empty ballot box padlocked shut with a red seal"),
    _e("El Ejército Rojo ya estaba ahí. Y quien tiene los tanques, escribe las reglas.",
       ["QUIEN TIENE", "LOS TANQUES"], ["ESCRIBE LAS REGLAS"], "g012",
       "a column of tanks parked in a town square while civilians watch from windows"),
    _e("Julio de mil novecientos cuarenta y cinco. En un desierto de Nuevo México, algo cambia para siempre.",
       ["JULIO 1945"], ["NUEVO MÉXICO"], "g013",
       "scientists in dark goggles watching a distant desert flash from a bunker"),
    _e("La primera bomba atómica funciona. Su creador piensa una sola frase: me he convertido en la muerte.",
       ["LA BOMBA"], ["FUNCIONA"], "g014",
       "a rising mushroom cloud over an empty desert with a tiny observation tower"),
    _e("Semanas después, Hiroshima y Nagasaki desaparecen en dos destellos.",
       ["HIROSHIMA"], ["NAGASAKI"], "g015",
       "a flattened Japanese city with one broken dome standing"),
    _e("Japón se rinde. Pero el mensaje también iba dirigido a Moscú: mira lo que tenemos.",
       ["EL MENSAJE"], ["ERA PARA MOSCÚ"], "g016",
       "a hand holding a small atomic bomb like a chess piece over a map"),
    _e("Stalin lo entiende perfectamente. Esa misma noche acelera su propio programa nuclear.",
       ["STALIN ENTIENDE"], ["Y ACELERA"], "g017",
       "Stalin at a desk at night signing a document beside an atom diagram"),
    _e("Mil novecientos cuarenta y seis. Churchill sube a un escenario y usa dos palabras que definen una época.",
       ["1946"], ["CHURCHILL HABLA"], "g018",
       "Churchill speaking at a podium in a university hall"),
    _e("Cortina de hierro. Así llamó a la línea invisible que partía Europa de norte a sur.",
       ["\"CORTINA", "DE HIERRO\""], ["DE NORTE A SUR"], "g019",
       "a tall iron curtain of riveted metal splitting a European landscape"),
    _e("A un lado, países que elegían gobierno. Al otro, países que obedecían a Moscú.",
       ["UN LADO ELIGE"], ["EL OTRO OBEDECE"], "g020",
       "a border fence with a voting queue on one side and marching soldiers on the other"),
    _e("Estados Unidos responde con una idea simple: si el comunismo avanza, hay que contenerlo.",
       ["LA CONTENCIÓN"], ["FRENAR EL AVANCE"], "g021",
       "a hand pressing a dam wall while red water pushes from the other side"),
    _e("Se llamó contención, y guió la política estadounidense durante cuarenta años.",
       ["40 AÑOS"], ["LA MISMA ESTRATEGIA"], "g022",
       "a long chain of soldiers standing shoulder to shoulder along a map border"),
    _e("Mil novecientos cuarenta y siete. Europa tiene hambre, frío y ninguna esperanza.",
       ["1947"], ["HAMBRE Y FRÍO"], "g023",
       "a queue of thin people with bowls in a snowy ruined street"),
    _e("Washington saca la billetera: trece mil millones de dólares para reconstruir el continente.",
       ["PLAN MARSHALL"], ["13.000 MILLONES"], "g024",
       "cargo ships unloading crates stamped with a small aid emblem at a European port"),
    _e("Se llamó Plan Marshall. Ayuda humanitaria, sí, pero también una jugada brillante.",
       ["AYUDA"], ["Y ESTRATEGIA"], "g025",
       "a chessboard where a bag of money is moved like a chess piece"),
    _e("Un país que vuelve a comer y a trabajar difícilmente vota comunista.",
       ["PAN"], ["CONTRA IDEOLOGÍA"], "g026",
       "a worker eating bread beside a rebuilt factory with smoking chimneys"),
    _e("Stalin prohíbe a sus países aceptar ese dinero. La frontera también se vuelve económica.",
       ["STALIN DICE NO"], ["FRONTERA ECONÓMICA"], "g027",
       "a hand refusing a bag of money across a barbed wire line"),
    _e("Mil novecientos cuarenta y ocho. Berlín está partida en cuatro pedazos, rodeada por territorio soviético.",
       ["BERLÍN"], ["PARTIDA EN CUATRO"], "g028",
       "a city map cut into four labeled sectors surrounded by shaded territory"),
    _e("Stalin decide asfixiarla: corta carreteras, trenes y canales. Nada entra por tierra.",
       ["EL BLOQUEO"], ["NADA ENTRA"], "g029",
       "a road barrier blocking a highway with a train stopped behind it"),
    _e("Dos millones de personas quedan atrapadas sin comida ni carbón.",
       ["2 MILLONES"], ["ATRAPADOS"], "g030",
       "families huddled with empty coal buckets in a dim apartment"),
    _e("La respuesta no fue una guerra. Fue un avión. Y otro. Y otro más.",
       ["LA RESPUESTA"], ["FUE UN AVIÓN"], "g031",
       "a cargo plane descending over Berlin rooftops while children wave"),
    _e("Durante once meses aterrizó un avión cada tres minutos con harina, leche y carbón.",
       ["11 MESES"], ["UN AVIÓN CADA", "3 MINUTOS"], "g032",
       "a busy airfield with several transport planes and crates being unloaded"),
    _e("Doscientos setenta y siete mil vuelos. Algunos pilotos lanzaban dulces con paracaídas caseros.",
       ["277.000 VUELOS"], ["Y DULCES CON", "PARACAÍDAS"], "g033",
       "small candy parcels with handkerchief parachutes falling toward cheering children"),
    _e("Stalin levanta el bloqueo. Perdió sin que nadie disparara. Pero Alemania queda dividida en dos países.",
       ["STALIN PIERDE"], ["ALEMANIA, DOS PAÍSES"], "g034",
       "a map of Germany split by a bold line, two flags on either side"),
    _e("Ese mismo año nace la OTAN: si atacan a uno, respondemos todos.",
       ["NACE LA OTAN"], ["UNO POR TODOS"], "g035",
       "twelve hands joined over a compass rose emblem"),
    _e("Los soviéticos contestan con el Pacto de Varsovia. Dos bloques, dos ejércitos, un solo continente.",
       ["PACTO DE", "VARSOVIA"], ["DOS BLOQUES"], "g036",
       "two facing rows of soldiers with a dividing line drawn between them"),
    _e("Mil novecientos cuarenta y nueve. Los soviéticos prueban su propia bomba atómica.",
       ["1949"], ["LA BOMBA SOVIÉTICA"], "g037",
       "a mushroom cloud over a bleak steppe with observation towers"),
    _e("Washington calculaba que tardarían años. Tardaron cuatro. Y con planos robados.",
       ["¿AÑOS?"], ["CUATRO. CON PLANOS", "ROBADOS"], "g038",
       "a spy passing a rolled blueprint under a streetlamp at night"),
    _e("Ahora los dos podían destruirse. Empieza la carrera más peligrosa de la historia.",
       ["LOS DOS PUEDEN"], ["DESTRUIRSE"], "g039",
       "two missiles standing side by side aimed at opposite skies"),
    _e("Ese año también cambia Asia: China se vuelve comunista tras una guerra civil brutal.",
       ["CHINA"], ["SE VUELVE COMUNISTA"], "g040",
       "Mao proclaiming from a high balcony above a large crowd"),
    _e("De golpe, un tercio de la humanidad vive bajo gobiernos comunistas.",
       ["UN TERCIO"], ["DE LA HUMANIDAD"], "g041",
       "a pie chart drawn as a globe with one third shaded red"),
    _e("Mil novecientos cincuenta. Corea está dividida por una línea trazada casi al azar.",
       ["1950"], ["COREA DIVIDIDA"], "g042",
       "a map of the Korean peninsula with a horizontal line across its middle"),
    _e("El norte invade el sur. Y por primera vez, los dos bloques pelean de verdad.",
       ["EL NORTE INVADE"], ["LA PRIMERA GUERRA", "CALIENTE"], "g043",
       "soldiers advancing through a rice field with tanks behind them"),
    _e("Aviones estadounidenses contra pilotos soviéticos disfrazados de chinos. Un secreto a gritos.",
       ["PILOTOS SECRETOS"], ["UN SECRETO A GRITOS"], "g044",
       "two jet fighters in a dogfight over snowy hills"),
    _e("Tres años de combates. Tres millones de muertos. Y la frontera quedó exactamente igual.",
       ["3 MILLONES"], ["Y TODO IGUAL"], "g045",
       "two soldiers facing each other across the same border line, exhausted"),
    _e("Corea sigue dividida hoy. Técnicamente, esa guerra nunca terminó.",
       ["SIGUE DIVIDIDA"], ["LA GUERRA NO TERMINÓ"], "g046",
       "a modern fortified border fence with watchtowers and empty road"),
    _e("Mientras tanto, en Estados Unidos crece un miedo distinto: el enemigo interno.",
       ["EL MIEDO"], ["AL ENEMIGO INTERNO"], "g047",
       "a suspicious crowd looking sideways at one nervous man"),
    _e("Un senador llamado McCarthy dice tener listas de comunistas infiltrados en el gobierno.",
       ["McCARTHY"], ["\"TENGO LISTAS\""], "g048",
       "a senator waving a sheet of paper at a hearing table with microphones"),
    _e("Nunca mostró pruebas sólidas, pero destruyó carreras, familias y reputaciones.",
       ["SIN PRUEBAS"], ["CARRERAS DESTRUIDAS"], "g049",
       "a man leaving an office with a cardboard box while colleagues stare"),
    _e("Actores, escritores y científicos quedaron en listas negras por sospechas.",
       ["LISTAS NEGRAS"], ["SOLO POR SOSPECHAS"], "g050",
       "a black list of crossed-out names pinned to a studio wall"),
    _e("En las escuelas, los niños practicaban esconderse bajo el pupitre por si caía una bomba.",
       ["BAJO EL PUPITRE"], ["POR SI CAE LA BOMBA"], "g051",
       "schoolchildren crouching under wooden desks during a drill"),
    _e("Mil novecientos cincuenta y dos. Estados Unidos prueba la bomba de hidrógeno.",
       ["1952"], ["BOMBA DE HIDRÓGENO"], "g052",
       "a huge explosion cloud over a tiny Pacific atoll"),
    _e("Era casi mil veces más potente que la de Hiroshima. La isla donde explotó ya no existe.",
       ["1.000 VECES MÁS"], ["LA ISLA DESAPARECIÓ"], "g053",
       "an empty crater of water where an island used to be, drawn as a map inset"),
    _e("Los soviéticos consiguen la suya un año después. Otra vez empatados, pero más arriba.",
       ["EMPATE"], ["MÁS ARRIBA"], "g054",
       "two hands stacking equal towers of bombs higher and higher"),
    _e("Mil novecientos cincuenta y tres. Muere Stalin. Millones lloran a un hombre que los aterrorizaba.",
       ["MUERE STALIN"], ["1953"], "g055",
       "an enormous funeral procession with a portrait carried above the crowd"),
    _e("Lo reemplaza Jrushchov, un hombre bajito, campesino, imprevisible y con mucho carácter.",
       ["JRUSHCHOV"], ["IMPREVISIBLE"], "g056",
       "Khrushchev gesturing energetically while speaking"),
    _e("En un discurso secreto denuncia los crímenes de Stalin. La sala queda helada.",
       ["DISCURSO SECRETO"], ["LA SALA, HELADA"], "g057",
       "a hall of stunned delegates listening in silence to a speaker"),
    _e("Habla de deshielo. Y por un momento, el mundo respira.",
       ["EL DESHIELO"], ["EL MUNDO RESPIRA"], "g058",
       "an ice block melting into water beside two shaking hands"),
    _e("Mil novecientos cincuenta y seis. Hungría se lo cree y sale a la calle a pedir libertad.",
       ["1956"], ["HUNGRÍA SALE", "A LA CALLE"], "g059",
       "a crowd marching with a flag with a hole cut in its center"),
    _e("Doce días de esperanza. Después llegan dos mil tanques soviéticos.",
       ["12 DÍAS"], ["2.000 TANQUES"], "g060",
       "tanks rolling into a European boulevard while people throw stones"),
    _e("Miles de muertos. El mensaje fue claro: se puede criticar a Stalin, pero no salir del bloque.",
       ["EL MENSAJE"], ["NADIE SE VA"], "g061",
       "a heavy door slammed shut with a chain across it"),
    _e("Ese mismo año, Egipto nacionaliza el Canal de Suez y Occidente se pelea consigo mismo.",
       ["SUEZ"], ["OCCIDENTE SE PELEA"], "g062",
       "ships blocked in a narrow canal with soldiers on the banks"),
    _e("Estados Unidos frena a sus propios aliados. Queda claro quién manda en el bloque occidental.",
       ["QUEDA CLARO"], ["QUIÉN MANDA"], "g063",
       "a large hand stopping two smaller marching soldiers"),
    _e("Cuatro de octubre de mil novecientos cincuenta y siete. Una bolita de metal cambia todo.",
       ["4-10-1957"], ["UNA BOLITA DE METAL"], "g064",
       "a small metal sphere with four antennas orbiting above the Earth"),
    _e("El Sputnik pasa sobre Estados Unidos haciendo bip. Y nadie puede hacer nada.",
       ["SPUTNIK"], ["BIP... BIP..."], "g065",
       "a family in a garden looking up at a moving dot in the night sky with a radio"),
    _e("Si podían poner eso en órbita, también podían poner una bomba sobre Nueva York.",
       ["SI SUBE ESO"], ["TAMBIÉN SUBE UNA", "BOMBA"], "g066",
       "a rocket trajectory arc drawn from one continent to another over a globe"),
    _e("El pánico es enorme. Estados Unidos crea la NASA y reforma la enseñanza de ciencias.",
       ["NACE LA NASA"], ["Y CAMBIA LA ESCUELA"], "g067",
       "students in a science classroom with a rocket model on the teacher's desk"),
    _e("Mil novecientos sesenta y uno. Yuri Gagarin se convierte en el primer humano en el espacio.",
       ["GAGARIN"], ["PRIMER HUMANO", "EN EL ESPACIO"], "g068",
       "a cosmonaut smiling inside a round capsule window"),
    _e("Los soviéticos van ganando la carrera espacial, y lo festejan en cada portada del mundo.",
       ["VAN GANANDO"], ["Y LO FESTEJAN"], "g069",
       "newspaper front pages pinned together showing a cosmonaut"),
    _e("Kennedy responde con una promesa loca: llegaremos a la Luna antes de que termine la década.",
       ["KENNEDY PROMETE"], ["LA LUNA"], "g070",
       "Kennedy speaking at a stadium podium pointing upward"),
    _e("Ese mismo año, Berlín vuelve al centro del tablero.",
       ["BERLÍN"], ["OTRA VEZ"], "g071",
       "a divided city street with a checkpoint booth in the middle"),
    _e("Tres millones de personas habían escapado del este cruzando la ciudad.",
       ["3 MILLONES"], ["SE ESCAPARON"], "g072",
       "a long line of people with suitcases walking toward a checkpoint"),
    _e("Se iban los médicos, los ingenieros, los jóvenes. El país se vaciaba.",
       ["SE IBAN LOS", "MÉDICOS"], ["EL PAÍS SE VACIABA"], "g073",
       "empty hospital and workshop with abandoned coats and tools"),
    _e("Una noche de agosto, los berlineses se despiertan con alambre de púas cruzando su ciudad.",
       ["UNA NOCHE"], ["ALAMBRE DE PÚAS"], "g074",
       "soldiers unrolling barbed wire across a city street at dawn"),
    _e("En pocos días, el alambre se vuelve un muro de concreto de ciento cincuenta kilómetros.",
       ["EL MURO"], ["150 KILÓMETROS"], "g075",
       "workers laying concrete blocks to build a tall wall through a neighborhood"),
    _e("Familias quedaron separadas en veredas distintas. Algunos se despidieron con la mano durante años.",
       ["FAMILIAS"], ["SEPARADAS"], "g076",
       "people waving handkerchiefs to each other over a wall"),
    _e("Muchos intentaron cruzar en túneles, en globos, en autos con doble fondo. Muchos no lo lograron.",
       ["TÚNELES Y GLOBOS"], ["MUCHOS NO LOGRARON"], "g077",
       "a homemade hot air balloon rising over a wall at night"),
    _e("Octubre de mil novecientos sesenta y dos. Trece días en los que el mundo casi termina.",
       ["OCTUBRE 1962"], ["13 DÍAS"], "g078",
       "a wall calendar with thirteen days circled in dark ink"),
    _e("Un avión espía fotografía rampas de misiles soviéticos en Cuba.",
       ["MISILES"], ["EN CUBA"], "g079",
       "a reconnaissance photograph of missile launch pads among palm trees"),
    _e("A ciento cincuenta kilómetros de Florida. Tiempo de aviso: cinco minutos.",
       ["150 KM"], ["5 MINUTOS DE AVISO"], "g080",
       "a map showing an arc from Cuba to Florida with a stopwatch"),
    _e("Kennedy reúne a sus asesores. La mitad quiere bombardear la isla ya mismo.",
       ["LA MITAD QUIERE"], ["BOMBARDEAR"], "g081",
       "tense advisers arguing around a table with maps and photographs"),
    _e("Elige algo intermedio: un bloqueo naval. Los barcos soviéticos siguen avanzando.",
       ["BLOQUEO NAVAL"], ["Y SIGUEN AVANZANDO"], "g082",
       "warships forming a line at sea while cargo ships approach"),
    _e("El mundo mira la televisión sin respirar. Las escuelas practican simulacros reales.",
       ["EL MUNDO"], ["SIN RESPIRAR"], "g083",
       "a family watching a small television set in a living room at night"),
    _e("Un submarino soviético, aislado y bombardeado con cargas de aviso, casi lanza un torpedo nuclear.",
       ["UN SUBMARINO"], ["CASI LO LANZA"], "g084",
       "a submarine crew sweating in a cramped control room with dials"),
    _e("Un oficial llamado Arjípov se negó. Probablemente le salvó la vida a millones de personas.",
       ["UN HOMBRE"], ["DIJO NO"], "g085",
       "a naval officer raising a hand in refusal inside a submarine"),
    _e("Al final hubo acuerdo: los soviéticos retiran los misiles, Estados Unidos promete no invadir Cuba.",
       ["ACUERDO"], ["SE RETIRAN LOS", "MISILES"], "g086",
       "missiles being loaded back onto a ship deck under tarpaulins"),
    _e("Y en secreto, también saca sus misiles de Turquía. Los dos ganaron algo. Y el mundo respiró.",
       ["EN SECRETO"], ["LOS DOS GANARON"], "g087",
       "two hands shaking behind a curtain with missiles fading away"),
    _e("El susto fue tan grande que instalaron una línea directa entre Moscú y Washington.",
       ["LÍNEA DIRECTA"], ["MOSCÚ-WASHINGTON"], "g088",
       "a telephone with a long cable stretching between two distant buildings"),
    _e("Nunca fue un teléfono rojo, aunque el cine lo pintó así.",
       ["NO ERA ROJO"], ["ERA UN TELETIPO"], "g089",
       "an old teletype machine printing a message strip"),
    _e("Mil novecientos sesenta y cinco. La Guerra Fría encuentra un nuevo escenario: Vietnam.",
       ["1965"], ["VIETNAM"], "g090",
       "American helicopters landing in a jungle clearing with soldiers jumping out"),
    _e("Estados Unidos manda medio millón de soldados a una selva que no conocía.",
       ["500.000"], ["SOLDADOS"], "g091",
       "soldiers wading through a river in dense jungle with heavy packs"),
    _e("Enfrente, un ejército que se escondía en túneles y peleaba con paciencia infinita.",
       ["TÚNELES"], ["Y PACIENCIA"], "g092",
       "a fighter emerging from a hidden tunnel entrance in the jungle floor"),
    _e("Fue la primera guerra televisada. Las familias veían el combate durante la cena.",
       ["LA GUERRA"], ["EN LA TELEVISIÓN"], "g093",
       "a television showing combat footage in front of a dinner table"),
    _e("Y lo que veían no coincidía con lo que decían los comunicados oficiales.",
       ["LO OFICIAL"], ["NO COINCIDÍA"], "g094",
       "an official at a podium beside a screen showing a contradictory image"),
    _e("Mil novecientos sesenta y ocho. Los jóvenes explotan en medio mundo.",
       ["1968"], ["EXPLOTA TODO"], "g095",
       "a huge student protest march with handmade signs"),
    _e("En París, en México, en Estados Unidos: protestas contra la guerra y contra todo lo heredado.",
       ["PARÍS. MÉXICO."], ["PROTESTAS"], "g096",
       "students building a street barricade with cobblestones and chairs"),
    _e("En Praga también quieren cambiar las cosas: un socialismo con rostro humano.",
       ["PRAGA"], ["ROSTRO HUMANO"], "g097",
       "a crowd in a European square with hopeful banners"),
    _e("Moscú responde con tanques. Un joven se para frente a uno con el pecho descubierto.",
       ["TANQUES"], ["Y UN JOVEN SOLO"], "g098",
       "a young man standing bare-chested in front of a tank in a city street"),
    _e("Esa imagen recorrió el mundo. La esperanza duró exactamente ocho meses.",
       ["8 MESES"], ["DE ESPERANZA"], "g099",
       "a wilting flower placed on a tank tread"),
    _e("Veinte de julio de mil novecientos sesenta y nueve. Un hombre baja una escalera y pisa la Luna.",
       ["20-07-1969"], ["LA LUNA"], "g100",
       "an astronaut boot print on lunar dust with the lunar module behind"),
    _e("Seiscientos millones de personas lo ven en vivo. Estados Unidos gana la carrera espacial.",
       ["600 MILLONES"], ["MIRANDO"], "g101",
       "crowds watching a giant public screen showing a spacecraft"),
    _e("Los soviéticos, que habían llegado primero al espacio, esa noche no dijeron casi nada.",
       ["SILENCIO"], ["EN MOSCÚ"], "g102",
       "an empty newsroom with a blank front page and a quiet radio"),
    _e("Años setenta. Los dos bloques están agotados y carísimos. Es hora de negociar.",
       ["AÑOS 70"], ["HORA DE NEGOCIAR"], "g103",
       "two exhausted boxers sitting in opposite corners of a ring"),
    _e("Firman tratados para limitar misiles. Se llamó distensión: no amistad, pero sí menos gritos.",
       ["DISTENSIÓN"], ["MENOS GRITOS"], "g104",
       "diplomats signing treaty documents and shaking hands over a long table"),
    _e("Incluso una nave estadounidense y una soviética se acoplan en el espacio y sus tripulantes se dan la mano.",
       ["EN EL ESPACIO"], ["SE DAN LA MANO"], "g105",
       "two docked spacecraft with astronauts shaking hands through the hatch"),
    _e("Mil novecientos setenta y nueve. La Unión Soviética invade Afganistán y la distensión se termina.",
       ["1979"], ["AFGANISTÁN"], "g106",
       "a Soviet armored column entering a mountain pass while fighters watch from a ridge"),
    _e("Fue su Vietnam: nueve años, montañas imposibles y una guerra que no se podía ganar.",
       ["9 AÑOS"], ["SU PROPIO VIETNAM"], "g107",
       "soldiers climbing a rocky mountain path with a damaged helicopter behind"),
    _e("Estados Unidos armó a la resistencia. Décadas después, esas armas seguirían causando problemas.",
       ["ARMAS"], ["QUE VOLVERÍAN"], "g108",
       "crates of rifles being handed over on a mountain trail"),
    _e("Mil novecientos ochenta. En unos astilleros polacos, unos obreros hacen algo impensable: se organizan.",
       ["1980"], ["ASTILLEROS POLACOS"], "g109",
       "shipyard workers gathered at a factory gate with a handwritten banner"),
    _e("Un electricista llamado Lech Walesa lidera un sindicato libre en un país comunista.",
       ["SOLIDARIDAD"], ["UN SINDICATO LIBRE"], "g110",
       "a mustached worker speaking to a crowd from atop a gate"),
    _e("Diez millones de miembros. El bloque empieza a crujir desde adentro.",
       ["10 MILLONES"], ["EL BLOQUE CRUJE"], "g111",
       "a cracking concrete wall with a small plant growing through the crack"),
    _e("Mil novecientos ochenta y uno. Llega Reagan, y el tono vuelve a endurecerse.",
       ["REAGAN"], ["SE ENDURECE EL TONO"], "g112",
       "Reagan speaking at an outdoor podium with flags behind"),
    _e("Lo llama el imperio del mal y lanza el mayor gasto militar en tiempos de paz.",
       ["\"IMPERIO", "DEL MAL\""], ["MÁS GASTO MILITAR"], "g113",
       "a rising bar chart made of missiles and dollar signs"),
    _e("Propone un escudo espacial que dispare a los misiles enemigos. La prensa lo llama Guerra de las Galaxias.",
       ["ESCUDO ESPACIAL"], ["\"GUERRA DE LAS", "GALAXIAS\""], "g114",
       "a satellite firing a beam at an incoming missile above the Earth"),
    _e("Nunca funcionó del todo, pero obligó a los soviéticos a gastar dinero que ya no tenían.",
       ["NO FUNCIONÓ"], ["PERO LOS OBLIGÓ", "A GASTAR"], "g115",
       "an empty treasury vault with a single coin rolling away"),
    _e("Mil novecientos ochenta y tres. Un satélite soviético detecta cinco misiles enemigos. Era un error.",
       ["1983"], ["FALSA ALARMA"], "g116",
       "a radar screen with five blinking dots and an alarm light"),
    _e("El oficial de guardia decidió no informarlo. Cinco misiles eran muy pocos para ser un ataque real.",
       ["DECIDIÓ NO", "INFORMAR"], ["Y ACERTÓ"], "g117",
       "an officer alone at a control console deciding, hand hovering over a phone"),
    _e("Se llamaba Petrov. Otro hombre común que evitó el fin del mundo.",
       ["PETROV"], ["OTRO HOMBRE COMÚN"], "g118",
       "a plain man in uniform standing quietly with a globe behind him"),
    _e("Mil novecientos ochenta y cinco. Llega Gorbachov, y trae dos palabras nuevas.",
       ["GORBACHOV"], ["DOS PALABRAS NUEVAS"], "g119",
       "Gorbachev speaking with papers in hand at a microphone"),
    _e("Glasnost: hablar con la verdad. Perestroika: reconstruir la economía.",
       ["GLASNOST"], ["PERESTROIKA"], "g120",
       "an open window letting light into a dark room full of old files"),
    _e("Quería salvar el sistema. Sin saberlo, le abrió la puerta de salida.",
       ["QUERÍA SALVARLO"], ["ABRIÓ LA PUERTA"], "g121",
       "a hand opening a heavy door with bright light behind it"),
    _e("Mil novecientos ochenta y seis. Explota el reactor de Chernóbil y el Estado intenta ocultarlo.",
       ["CHERNÓBIL"], ["1986"], "g122",
       "a ruined reactor building with smoke and firefighters at a distance"),
    _e("La nube radioactiva llegó a Suecia antes que la información a los propios vecinos.",
       ["LA NUBE"], ["LLEGÓ ANTES QUE", "LA VERDAD"], "g123",
       "a drifting cloud over a map of Europe with a warning sign"),
    _e("Chernóbil fue el golpe final a la confianza en el sistema soviético.",
       ["EL GOLPE"], ["A LA CONFIANZA"], "g124",
       "an abandoned amusement park ferris wheel with an empty city behind"),
    _e("Mil novecientos ochenta y siete. Reagan, frente al muro, dice una frase que queda para siempre.",
       ["1987"], ["FRENTE AL MURO"], "g125",
       "a leader speaking at a podium in front of a large gate and wall"),
    _e("Señor Gorbachov, derribe ese muro. Dos años después, alguien lo hizo. Pero no fue un presidente.",
       ["\"DERRIBE", "ESE MURO\""], ["Y ALGUIEN LO HIZO"], "g126",
       "a hand holding a hammer near a concrete wall"),
    _e("Mil novecientos ochenta y nueve. Los países del este empiezan a soltarse uno por uno.",
       ["1989"], ["UNO POR UNO"], "g127",
       "a row of dominoes falling across a map of Eastern Europe"),
    _e("Polonia vota. Hungría abre su frontera. Y nadie manda tanques esta vez.",
       ["ESTA VEZ"], ["NO HAY TANQUES"], "g128",
       "a border gate being lifted while people walk through freely"),
    _e("Nueve de noviembre. Un vocero se confunde en una conferencia de prensa y dice que las fronteras están abiertas.",
       ["9 DE NOVIEMBRE"], ["UN ERROR EN VIVO"], "g129",
       "a spokesman at a press conference reading a note under camera lights"),
    _e("Miles de personas van al muro. Los guardias no saben qué hacer y levantan las barreras.",
       ["MILES VAN"], ["AL MURO"], "g130",
       "a huge crowd pressing against a checkpoint barrier at night"),
    _e("Esa noche, la gente baila arriba del muro y lo rompe con martillos y las manos.",
       ["ESA NOCHE"], ["BAILARON ARRIBA"], "g131",
       "people standing and celebrating on top of the Berlin Wall with hammers"),
    _e("Familias que llevaban veintiocho años separadas se abrazan en la calle.",
       ["28 AÑOS"], ["Y UN ABRAZO"], "g132",
       "two families embracing in the middle of an open border crossing"),
    _e("Un año después, Alemania vuelve a ser un solo país.",
       ["ALEMANIA"], ["OTRA VEZ UNA"], "g133",
       "two halves of a map joining together with a flag above"),
    _e("Mil novecientos noventa y uno. La Unión Soviética se deshace en quince países.",
       ["1991"], ["15 PAÍSES"], "g134",
       "a map coming apart into fifteen separate pieces"),
    _e("El veinticinco de diciembre bajan la bandera roja del Kremlin. Sin batallas, sin disparos.",
       ["BAJAN"], ["LA BANDERA ROJA"], "g135",
       "a flag being lowered from a Kremlin tower against a winter sky"),
    _e("Así terminó la guerra más larga sin combates directos de la historia.",
       ["FIN"], ["DE LA GUERRA FRÍA"], "g136",
       "two rifles laid down crossed on the ground with snow falling"),
    _e("Dejó fronteras nuevas, países partidos y unas cincuenta mil bombas nucleares en el planeta.",
       ["50.000"], ["BOMBAS NUCLEARES"], "g137",
       "rows of small missile silos drawn across a world map"),
    _e("También dejó satélites, internet, viajes espaciales y muchas cosas que hoy usamos todos los días.",
       ["TAMBIÉN DEJÓ"], ["LO QUE USAS HOY"], "g138",
       "a satellite, a computer and a rocket drawn together in one sketch"),
    _e("Y dejó una lección incómoda: el mundo se salvó varias veces porque alguien común decidió no obedecer.",
       ["LA LECCIÓN"], ["ALGUIEN DIJO NO"], "g139",
       "an ordinary person standing firm while a huge shadow of a missile looms"),
    _e("Cuarenta y cinco años de miedo. Y ni un solo disparo entre los dos gigantes.",
       ["45 AÑOS"], ["NI UN DISPARO"], "g140",
       "a child sitting on a graffiti-covered fragment of the Berlin Wall"),
    _e("Esta fue la Guerra Fría. Si te gustó, quédate: la historia siempre tiene otro capítulo.",
       ["LA GUERRA FRÍA"], ["GRACIAS POR VER"], "g141",
       "two unclenching hands with a dove flying between them and a faint globe", gap=0.9),
]
