"""Guion completo de EL ALUNIZAJE — la historia entera, contada en detalle.

Reglas fijas del proyecto:
  * Narrador único: Dark.
  * Los nombres en inglés se escriben tal como suenan en español, para que el
    generador los pronuncie bien (Kennedy -> Quénedi, Armstrong -> Ármstrong).
  * Las fechas y los años van SIEMPRE en cifras.
  * La letra de pantalla es estática mientras se escribe.
  * Sin música de fondo: solo voz, dibujo y silencio.

Cada entrada: S(texto, pausa, imagen, titulo, subtitulo)
  texto     -> lo que dice el narrador (con grafía fonética donde hace falta)
  pausa     -> segundos de silencio después de la frase
  imagen    -> clave del dibujo (o None)
  titulo    -> hasta 3 líneas cortas separadas por "|"  (letra grande)
  subtitulo -> hasta 3 líneas separadas por "|"        (letra mediana)
"""


def S(texto, pausa=0.35, img=None, t1=None, t2=None):
    return dict(txt=texto, gap=pausa, img=img,
                t1=t1.split('|') if t1 else None,
                t2=t2.split('|') if t2 else None)


GUION = [
    # ---------------------------------------------------------------- APERTURA
    S("Salí una noche al patio... y mirá para arriba. Ahí está: la Luna.", 0.45,
      'luna', "EL ALUNIZAJE", "LA HISTORIA COMPLETA"),
    S("La misma que vieron los egipcios, los romanos... y tu bisabuelo. Blanca. Quieta. Inalcanzable.", 0.5,
      'patio', "LA MISMA LUNA", "DE LOS EGIPCIOS|Y DE TU BISABUELO"),
    S("Durante miles de años fue el techo del mundo. Nadie, jamás, pensó seriamente en tocarla.", 0.45,
      None, "EL TECHO|DEL MUNDO", "NADIE PENSABA EN TOCARLA"),
    S("Y en apenas ocho años, un grupo de personas con reglas de cálculo y café frío, la pisó.", 0.55,
      'saturno', "OCHO AÑOS", "REGLAS DE CÁLCULO|Y CAFÉ FRÍO"),
    S("Esta es la historia completa. Con los nombres, las fechas, los errores... y los muertos.", 0.6,
      None, "LA HISTORIA|COMPLETA", "NOMBRES. FECHAS.|ERRORES. MUERTOS."),

    # ------------------------------------------------------- EL MIEDO DE FONDO
    S("Pero para entenderla hay que empezar antes. Mucho antes de que alguien hablara de la Luna.", 0.4,
      None, "EMPECEMOS|POR EL PRINCIPIO", None),
    S("Terminó la Segunda Guerra Mundial, y quedaron dos gigantes mirándose de frente: Estados Unidos y la Unión Soviética.", 0.45,
      'carrera', "DOS GIGANTES", "ESTADOS UNIDOS|UNIÓN SOVIÉTICA"),
    S("No podían dispararse. Los dos tenían bombas atómicas. Así que compitieron en todo lo demás.", 0.5,
      None, "NO PODÍAN|DISPARARSE", "COMPITIERON|EN TODO LO DEMÁS"),
    S("Y el cielo se convirtió en el campo de juego. Porque quien controlaba el cielo... controlaba el mundo.", 0.55,
      'carrera', "EL CIELO", "QUIEN LO CONTROLA|CONTROLA EL MUNDO"),
    S("Los dos bandos tenían la misma herencia incómoda: los cohetes alemanes de la guerra.", 0.4,
      'v2cohete', "LOS COHETES|ALEMANES", "UNA HERENCIA INCÓMODA"),
    S("Los uve dos que cayeron sobre Londres eran, en el fondo, la primera nave que rozó el espacio.", 0.45,
      'v2cohete', "LA UVE DOS", "LA PRIMERA EN|ROZAR EL ESPACIO"),
    S("Cuando cayó Alemania, americanos y soviéticos salieron a buscar lo mismo: no oro, no cuadros. Ingenieros.", 0.5,
      None, "SALIERON A BUSCAR", "NO ORO.|INGENIEROS."),
    S("Los estadounidenses se llevaron a Vérner fon Braun, el hombre que había diseñado esos cohetes.", 0.45,
      'vonbraun', "VERNHER|VON BRAUN", "EL DISEÑADOR|DE LOS COHETES"),
    S("Un tipo brillante, y con un pasado muy oscuro. Pero soñaba con algo que nadie más se animaba a decir en voz alta.", 0.45,
      'vonbraun', "BRILLANTE", "Y CON UN PASADO|MUY OSCURO"),
    S("Fon Braun no quería armas. Quería ir a Marte. Y para eso, primero, había que ir a la Luna.", 0.55,
      None, "ÉL NO QUERÍA|ARMAS", "QUERÍA IR A MARTE"),
    S("Del otro lado, los soviéticos tenían a alguien mejor. Y durante años, nadie supo ni su nombre.", 0.5,
      'korolev', "DEL OTRO LADO", "ALGUIEN MEJOR|Y SECRETO"),
    S("Le decían, simplemente, el Diseñador Jefe. Se llamaba Serguéi Koroliov.", 0.45,
      'korolev', "SERGUÉI|KOROLIOV", "EL DISEÑADOR JEFE"),
    S("Había estado preso en un campo de trabajo en Siberia, acusado sin pruebas. Le rompieron la mandíbula. Perdió los dientes.", 0.5,
      'korolev', "PRESO EN SIBERIA", "ACUSADO SIN PRUEBAS"),
    S("Salió de ahí, y construyó el programa espacial más adelantado del planeta. Su identidad era secreto de Estado.", 0.6,
      None, "SALIÓ Y CONSTRUYÓ", "SECRETO DE ESTADO"),

    # ------------------------------------------------------------------ 1957
    S("4 de octubre de 1957. Un martes cualquiera se convirtió en el día que cambió todo.", 0.4,
      'sputnik', "4 DE OCTUBRE|DE 1957", "EL DÍA QUE|CAMBIÓ TODO"),
    S("Los soviéticos lanzaron el Espútnik: una bola de metal de ochenta y tres kilos, con cuatro antenas.", 0.45,
      'sputnik', "SPUTNIK", "83 KILOS|CUATRO ANTENAS"),
    S("No hacía nada. Solo daba vueltas alrededor de la Tierra... y hacía bip.", 0.5,
      'sputnik', "SOLO HACÍA|BIP", "PERO ERA SUFICIENTE"),
    S("Y ese bip lo podía escuchar cualquiera con una radio. Incluso desde el patio de una casa en Estados Unidos.", 0.5,
      None, "CUALQUIERA|LO ESCUCHABA", "DESDE SU PROPIA CASA"),
    S("Ahí llegó el pánico. Porque si podían poner una bola de metal sobre tu cabeza... también podían poner otra cosa.", 0.6,
      None, "SI PONEN ESO|AHÍ ARRIBA", "TAMBIÉN PUEDEN|PONER OTRA COSA"),
    S("Un mes después mandaron a Láika, una perrita callejera de Moscú. Murió a las pocas horas por el calor.", 0.5,
      'laika', "LAIKA", "UNA PERRA CALLEJERA|DE MOSCÚ"),
    S("Nunca hubo plan para traerla de vuelta. Y eso también dice algo sobre cómo era esa carrera.", 0.55,
      'laika', "NO HABÍA PLAN|DE VUELTA", "ASÍ ERA LA CARRERA"),
    S("Estados Unidos respondió apurado. Su primer cohete, el Vanguard, explotó en la plataforma, en vivo, por televisión.", 0.45,
      'fracaso', "LA RESPUESTA", "EXPLOTÓ EN VIVO|POR TELEVISIÓN"),
    S("Los diarios lo bautizaron con nombres crueles: FlupNik Kaputnik. La humillación fue total.", 0.55,
      'fracaso', "FLOPNIK|KAPUTNIK", "HUMILLACIÓN TOTAL"),
    S("El 29 de julio de 1958 nació la Nása. Una agencia civil, no militar. Y con una sola orden: alcanzarlos.", 0.5,
      'nasa', "29 JULIO 1958", "NACE LA NASA|ALCANZARLOS"),

    # ------------------------------------------------------------- MERCURY
    S("El primer plan se llamó Proyecto Mércuri. Objetivo: meter a un hombre en una cápsula y que vuelva vivo.", 0.4,
      'mercury', "PROYECTO|MERCURY", "UN HOMBRE|Y QUE VUELVA VIVO"),
    S("Eligieron a siete pilotos de prueba. Los presentaron como héroes antes de que hicieran absolutamente nada.", 0.5,
      'mercury7', "LOS SIETE|DE MERCURY", "HÉROES ANTES|DE HACER NADA"),
    S("La cápsula era tan chica que decían, en broma, que no te subías: te la ponías.", 0.5,
      'mercury', "TAN CHICA", "NO TE SUBÍAS:|TE LA PONÍAS"),
    S("Pero otra vez llegaron tarde. 12 de abril de 1961: Iúri Gagárin dio una vuelta completa al planeta.", 0.45,
      'gagarin', "12 ABRIL 1961", "YURI GAGARIN|UNA VUELTA ENTERA"),
    S("Ciento ocho minutos. Y al bajar dijo una frase que quedó para siempre: la Tierra es azul.", 0.55,
      'gagarin', "108 MINUTOS", "«LA TIERRA ES AZUL»"),
    S("Veintitrés días después, Álan Shéperd hizo su vuelo. Duró quince minutos, y ni siquiera dio una vuelta.", 0.45,
      'mercury', "ALAN SHEPARD", "15 MINUTOS|SIN DAR LA VUELTA"),
    S("Ese era todo el currículum de Estados Unidos en vuelo tripulado. Quince minutos.", 0.6,
      None, "TODO EL|CURRÍCULUM", "QUINCE MINUTOS"),

    # ------------------------------------------------------------- LA PROMESA
    S("Y entonces, el 25 de mayo de 1961, un presidente joven se paró frente al Congreso.", 0.4,
      'kennedy', "25 MAYO 1961", "KENNEDY FRENTE|AL CONGRESO"),
    S("Esta nación debe poner un hombre en la Luna antes del fin de la década, y devolverlo sano y salvo.", 0.55,
      'congreso', "«UN HOMBRE|EN LA LUNA»", "ANTES DEL FIN|DE LA DÉCADA"),
    S("La sala aplaude. En la Nása... varios ingenieros se ponen pálidos.", 0.45,
      'ingenieros', "LA SALA APLAUDE", "EN LA NASA|SE PONEN PÁLIDOS"),
    S("Porque nadie sabía cómo hacerlo. No existía el cohete. No existía la nave. No existía la computadora.", 0.5,
      None, "NADIE SABÍA CÓMO", "NI COHETE. NI NAVE.|NI COMPUTADORA."),
    S("Ni siquiera sabían si el polvo lunar aguantaría el peso de una nave, o si se la iba a tragar.", 0.5,
      None, "NI SIQUIERA SABÍAN", "SI EL POLVO|LA AGUANTARÍA"),
    S("Quénedi no lo hizo por amor a la ciencia. Lo dijo él mismo en privado: quería ganarles a los soviéticos.", 0.5,
      'kennedy', "NO FUE POR|LA CIENCIA", "ERA POR GANARLES"),
    S("Pero a veces, un motivo mezquino puede empujar algo hermoso. Y esto fue exactamente eso.", 0.6,
      None, "UN MOTIVO|MEZQUINO", "EMPUJÓ ALGO HERMOSO"),
    S("Del dinero mejor ni hablemos: el programa se llevó cerca del cuatro por ciento del presupuesto del país.", 0.45,
      'dinero', "EL DINERO", "4% DEL PRESUPUESTO|DE UN PAÍS ENTERO"),
    S("Cuatrocientas mil personas trabajaron en esto. Costureras, soldadores, secretarias, matemáticas, cocineros.", 0.5,
      'equipo', "400.000|PERSONAS", "NO SOLO CIENTÍFICOS"),
    S("Casi ninguna de ellas iba a volar. Todas sabían que un error suyo podía matar a tres personas.", 0.6,
      'equipo', "CASI NINGUNA|IBA A VOLAR", "UN ERROR MATABA|A TRES"),

    # -------------------------------------------------------------- GEMINI
    S("Entre Mércuri y la Luna faltaba todo un escalón. Ese escalón se llamó Géminis.", 0.4,
      'gemini', "PROGRAMA|GEMINI", "EL ESCALÓN|QUE FALTABA"),
    S("Con Géminis había que aprender cosas que nadie había hecho jamás en la historia.", 0.45,
      None, "APRENDER LO QUE|NADIE HIZO", None),
    S("Salir de la nave y flotar afuera. Encontrarse con otra nave en órbita. Acoplarse. Vivir dos semanas allá arriba.", 0.5,
      'gemini', "SALIR. ENCONTRARSE.|ACOPLARSE.", "Y VIVIR DOS SEMANAS"),
    S("En 1965, Ed Uáit abrió la escotilla y salió al vacío atado por un cordón dorado.", 0.45,
      'white', "1965|ED WHITE", "SALE AL VACÍO"),
    S("Estuvo veintitrés minutos afuera. Cuando le ordenaron volver, dijo que era el momento más triste de su vida.", 0.55,
      'white', "23 MINUTOS|AFUERA", "«EL MOMENTO MÁS|TRISTE DE MI VIDA»"),
    S("En 1966, en el Géminis ocho, un joven llamado Neil Ármstrong logró el primer acople de la historia.", 0.4,
      'gemini8', "GEMINI 8", "NEIL ARMSTRONG|PRIMER ACOPLE"),
    S("Minutos después, la nave empezó a girar sola. Una vuelta por segundo. Ármstrong se estaba por desmayar.", 0.5,
      'gemini8', "EMPIEZA A GIRAR", "UNA VUELTA|POR SEGUNDO"),
    S("Apagó todo el sistema de maniobra, encendió los motores de reentrada, y la frenó a mano.", 0.5,
      'gemini8', "LA FRENÓ|A MANO", "SANGRE FRÍA PURA"),
    S("Ese día, en silencio, quedó claro quién era el piloto más frío del programa. Y eso, después, pesó.", 0.6,
      None, "AHÍ SE VIO", "QUIÉN ERA EL|MÁS FRÍO"),

    # ------------------------------------------------------------- APOLO 1
    S("Pero casi nadie cuenta cómo empezó de verdad el camino a la Luna. Empezó... con tres muertos.", 0.6,
      'tripulacion', "CÓMO EMPEZÓ|DE VERDAD", "CON TRES MUERTOS"),
    S("Ellos eran Vércheil Gas Grísom: veterano, y el segundo estadounidense en el espacio.", 0.35,
      'grissom', "VIRGIL «GUS»|GRISSOM", "VETERANO"),
    S("Ed Uáit: el primer norteamericano en caminar fuera de la nave.", 0.35,
      'white', "ED WHITE", "EL PRIMERO EN|CAMINAR AFUERA"),
    S("Y Róyer Cháfi: joven, ingeniero, a punto de volar por primera vez.", 0.5,
      'chaffee', "ROGER CHAFFEE", "A PUNTO DE VOLAR|POR PRIMERA VEZ"),
    S("Es el 27 de enero de 1967, y ni siquiera era un lanzamiento: era un ensayo en tierra.", 0.4,
      'prueba', "27 ENERO 1967", "NO ERA UN VUELO:|UN ENSAYO"),
    S("La cápsula del Apolo 1 estaba cerrada, y llena de oxígeno puro a presión.", 0.45,
      'prueba', "OXÍGENO PURO|A PRESIÓN", "LA CÁPSULA CERRADA"),
    S("Ya venían quejándose. Grísom había colgado un limón de la nave, como chiste amargo, porque nada funcionaba.", 0.5,
      'limon', "UN LIMÓN|COLGADO", "PORQUE NADA|FUNCIONABA"),
    S("Esa tarde, la radio fallaba. Grísom dijo: cómo vamos a llegar a la Luna si no podemos hablar entre dos edificios.", 0.55,
      'prueba', "FALLABA HASTA|LA RADIO", "«¿ASÍ VAMOS A IR|A LA LUNA?»"),
    S("Un cable pelado hizo una chispa. En oxígeno puro, todo lo que toca el fuego se convierte en combustible.", 0.45,
      'chispa', "UNA CHISPA", "TODO SE VUELVE|COMBUSTIBLE"),
    S("El velcro ardió. Las redes ardieron. Los trajes ardieron. La presión de adentro selló la puerta.", 0.5,
      'chispa', "TODO ARDIÓ", "LA PRESIÓN SELLÓ|LA PUERTA"),
    S("La escotilla se abría hacia adentro, y tardaba minutos en ceder. Los tres murieron en menos de treinta segundos.", 0.65,
      'escotilla', "LA ESCOTILLA|ABRÍA HACIA ADENTRO", "MENOS DE|30 SEGUNDOS"),
    S("Este es un negocio riesgoso.", 0.45,
      'grissom_cita', "«ESTE ES UN|NEGOCIO|RIESGOSO»", None),
    S("Lo había advertido Grísom meses antes. Y después del incendio, el programa entero se detuvo.", 0.5,
      None, "LO HABÍA|ADVERTIDO", "EL PROGRAMA|SE DETUVO"),
    S("La investigación fue brutal. Encontraron cables mal ruteados, herramientas olvidadas adentro, materiales que no debían estar ahí.", 0.5,
      'informe', "LA INVESTIGACIÓN", "CABLES MAL PUESTOS|HERRAMIENTAS ADENTRO"),
    S("Un ingeniero llamado Yin Cranz reunió a todo su equipo y les dijo una frase que se enseña hasta hoy.", 0.4,
      'kranz', "GENE KRANZ", "REÚNE A|SU EQUIPO"),
    S("Desde hoy somos duros y competentes. Duros: nunca más vamos a mirar para otro lado. Competentes: nunca más vamos a llegar sin saber.", 0.6,
      'kranz', "«DUROS Y|COMPETENTES»", "NUNCA MÁS MIRAR|PARA OTRO LADO"),
    S("Rediseñaron la nave entera. Escotilla que abre hacia afuera en siete segundos. Nada de oxígeno puro en tierra. Materiales que no arden.", 0.5,
      'huella', "LA REDISEÑARON|ENTERA", "ESCOTILLA HACIA AFUERA|EN 7 SEGUNDOS"),
    S("Y esa tragedia, aunque duela decirlo, fue lo que hizo posible llegar a la Luna.", 0.6,
      None, "ESA TRAGEDIA", "HIZO POSIBLE|LLEGAR"),

    # ------------------------------------------------------ LOS OTROS MUERTOS
    S("Del otro lado del mundo, los soviéticos también estaban pagando su precio, en silencio.", 0.4,
      None, "DEL OTRO LADO", "TAMBIÉN PAGABAN|EN SILENCIO"),
    S("En enero de 1966 murió Koroliov, en una operación que salió mal. Recién entonces el mundo supo su nombre.", 0.5,
      'korolev', "ENERO DE 1966", "MUERE KOROLIOV|Y RECIÉN AHÍ|SE SABE SU NOMBRE"),
    S("Sin él, el programa soviético empezó a desarmarse. Nadie más podía sostenerlo.", 0.5,
      None, "SIN ÉL", "TODO EMPEZÓ|A DESARMARSE"),
    S("En abril de 1967, Vladímir Komarov voló en una nave que él sabía que estaba fallada. Voló igual.", 0.5,
      'komarov', "VLADIMIR|KOMAROV", "SABÍA QUE LA NAVE|ESTABA FALLADA"),
    S("Voló para que no mandaran en su lugar a su amigo Gagárin. El paracaídas no abrió.", 0.6,
      'komarov', "VOLÓ POR|SU AMIGO", "EL PARACAÍDAS|NO ABRIÓ"),
    S("Cuatro hombres muertos en tres meses, en los dos bandos. Y ninguno de los dos se detuvo.", 0.6,
      None, "CUATRO MUERTOS|EN TRES MESES", "NINGUNO SE DETUVO"),

    # -------------------------------------------------------------- SATURNO V
    S("Mientras tanto, en Alabama, fon Braun terminaba la máquina más grande jamás construida.", 0.4,
      'saturno', "EN ALABAMA", "LA MÁQUINA MÁS|GRANDE JAMÁS HECHA"),
    S("El Saturno cinco medía ciento diez metros. Más alto que un edificio de treinta pisos.", 0.45,
      'saturno', "SATURNO V", "110 METROS|30 PISOS DE ALTO"),
    S("Pesaba casi tres mil toneladas al despegar. Y el noventa por ciento de ese peso era solo combustible.", 0.5,
      'saturno', "3.000 TONELADAS", "EL 90% ERA|COMBUSTIBLE"),
    S("Quemaba trece toneladas por segundo. Trece. Toneladas. Por segundo.", 0.55,
      'saturno', "13 TONELADAS|POR SEGUNDO", None),
    S("Cuando encendía, el ruido rompía ventanas a cinco kilómetros y hacía temblar el suelo de las tribunas.", 0.5,
      'lanzamiento', "ROMPÍA VENTANAS", "A CINCO KILÓMETROS"),
    S("Tenía seis millones de piezas. Si el noventa y nueve coma nueve por ciento funcionaba, quedaban seis mil fallando.", 0.6,
      'saturno', "6 MILLONES|DE PIEZAS", "99,9% BIEN =|6.000 FALLANDO"),

    # ---------------------------------------------------- LA COMPUTADORA
    S("Y arriba de todo eso, había que poner una computadora. En 1968 eso era casi ciencia ficción.", 0.4,
      'computadora', "UNA COMPUTADORA|ARRIBA DE TODO", "EN 1968"),
    S("La computadora del Apolo tenía menos memoria que la tarjeta más barata de un teléfono de hoy.", 0.5,
      'computadora', "MENOS MEMORIA", "QUE UN TELÉFONO|DE HOY"),
    S("La programó un equipo dirigido por una mujer de treinta y dos años: Márgaret Jámilton.", 0.45,
      'hamilton', "MARGARET|HAMILTON", "32 AÑOS"),
    S("Ella insistió en algo que sus jefes consideraban una pérdida de tiempo: preparar al programa para errores humanos.", 0.5,
      'hamilton', "ELLA INSISTIÓ", "PREPARAR PARA|EL ERROR HUMANO"),
    S("Le dijeron que los astronautas estaban entrenados, que no se equivocan. Ella lo programó igual.", 0.5,
      'hamilton', "«ELLOS NO SE|EQUIVOCAN»", "LO PROGRAMÓ IGUAL"),
    S("Guardá esa idea. Porque en el minuto más importante de todo esto, esa decisión salvó la misión.", 0.6,
      None, "GUARDÁ|ESA IDEA", "VA A SALVAR|LA MISIÓN"),

    # ---------------------------------------------------------- APOLO 7 y 8
    S("En octubre de 1968 voló el Apolo siete: la primera nave tripulada después del incendio. Funcionó.", 0.45,
      'apolo7', "OCTUBRE 1968", "APOLO 7|FUNCIONÓ"),
    S("Y entonces la Nása tomó la decisión más loca de todo el programa.", 0.5,
      None, "Y AHÍ TOMARON", "LA DECISIÓN|MÁS LOCA"),
    S("Corría el rumor de que los soviéticos iban a mandar una nave alrededor de la Luna antes de fin de año.", 0.45,
      None, "CORRÍA UN RUMOR", "LOS SOVIÉTICOS|IBAN A ADELANTARSE"),
    S("Así que cambiaron el plan sobre la marcha: el Apolo ocho, en su segundo vuelo, iría directo a la Luna.", 0.5,
      'apolo8', "CAMBIAN EL PLAN", "APOLO 8 VA|DIRECTO A LA LUNA"),
    S("Sin módulo lunar. Sin poder bajar. Solo tres hombres, un cohete nuevo, y cuatrocientos mil kilómetros de vacío.", 0.55,
      'apolo8', "SIN PODER BAJAR", "400.000 KILÓMETROS|DE VACÍO"),
    S("La esposa de uno de ellos le preguntó a un jefe qué probabilidades reales había. Le respondieron: cincuenta y cincuenta.", 0.6,
      None, "«¿QUÉ CHANCES|HAY?»", "CINCUENTA Y CINCUENTA"),
    S("El 24 de diciembre de 1968, en Nochebuena, el Apolo ocho dio diez vueltas alrededor de la Luna.", 0.45,
      'apolo8', "24 DICIEMBRE 1968", "DIEZ VUELTAS|A LA LUNA"),
    S("Detrás de la Luna se corta la radio. Durante treinta y cuatro minutos, nadie en la Tierra sabía si seguían vivos.", 0.55,
      'silencio', "34 MINUTOS|DE SILENCIO", "NADIE SABÍA|SI VIVÍAN"),
    S("Y cuando salieron del otro lado, uno de ellos miró por la ventanilla y gritó que agarraran la cámara.", 0.45,
      'tierra', "MIRÓ POR|LA VENTANILLA", "«AGARRÁ LA CÁMARA»"),
    S("Sobre el horizonte gris estaba saliendo la Tierra. Chiquita. Azul. Frágil. Sola.", 0.55,
      'tierra', "SALÍA LA TIERRA", "CHIQUITA. AZUL.|FRÁGIL. SOLA."),
    S("Esa foto se llamó Salida de la Tierra. Fuimos a descubrir la Luna, y terminamos descubriéndonos a nosotros mismos.", 0.65,
      'tierra', "FUIMOS A VER|LA LUNA", "Y NOS VIMOS|A NOSOTROS"),

    # ------------------------------------------------------------ ENSAYOS
    S("En marzo de 1969, el Apolo nueve probó el módulo lunar por primera vez, dando vueltas a la Tierra.", 0.4,
      'modulo', "MARZO 1969|APOLO 9", "PRUEBAN EL|MÓDULO LUNAR"),
    S("Ese módulo era, básicamente, una carpa de aluminio. En algunas partes, las paredes eran más finas que una lata.", 0.5,
      'modulo', "UNA CARPA|DE ALUMINIO", "PAREDES MÁS FINAS|QUE UNA LATA"),
    S("En mayo, el Apolo diez hizo el ensayo general: bajó a quince kilómetros de la superficie... y no aterrizó.", 0.5,
      'apolo10', "MAYO. APOLO 10", "BAJA A 15 KM|Y NO ATERRIZA"),
    S("Les habían cargado poco combustible a propósito. Por si les daban ganas de bajar igual.", 0.6,
      'apolo10', "POCO COMBUSTIBLE|A PROPÓSITO", "POR SI LES DABAN|GANAS DE BAJAR"),

    # --------------------------------------------------------- LA TRIPULACIÓN
    S("Y llegó julio de 1969. La tripulación del Apolo 11 no fue elegida por heroica, sino por rotación.", 0.4,
      'apolo11crew', "JULIO DE 1969", "LA TRIPULACIÓN|DEL APOLO 11"),
    S("Neil Ármstrong: civil, callado, casi imposible de alterar. El hombre que había frenado una nave a mano.", 0.45,
      'armstrong', "NEIL|ARMSTRONG", "CIVIL. CALLADO.|IMPOSIBLE DE ALTERAR."),
    S("Búzz Óldrin: doctor en encuentros orbitales. Tan obsesionado con el tema que le decían Doctor Rendevú.", 0.45,
      'aldrin', "BUZZ ALDRIN", "LE DECÍAN|«DOCTOR RENDEZVOUS»"),
    S("Y Máicol Cólins: el que se iba a quedar arriba, dando vueltas, sin bajar nunca.", 0.5,
      'collins', "MICHAEL|COLLINS", "SE QUEDA ARRIBA|SIN BAJAR"),
    S("Ármstrong firmó cientos de autógrafos antes de irse, para dejarle algo de plata a su familia. Por si no regresaba vívo", 0.6,
      None, "FIRMÓ CIENTOS|DE AUTÓGRAFOS", "PARA DEJARLE ALGO|A SU FAMILIA"),

    # ------------------------------------------------------------ LANZAMIENTO
    S("16 de julio de 1969. Un millón de personas se juntaron alrededor del cabo para verlo despegar.", 0.4,
      'lanzamiento', "16 JULIO 1969", "UN MILLÓN|DE PERSONAS"),
    S("A las nueve y treinta y dos de la mañana, el Saturno cinco encendió. Tardó doce segundos en despegar del piso.", 0.5,
      'lanzamiento', "9:32 DE|LA MAÑANA", "12 SEGUNDOS PARA|SOLTAR EL PISO"),
    S("Doce minutos después estaban en órbita. Después, un empujón más, y quedaron en camino a la Luna.", 0.5,
      'viaje', "12 MINUTOS|A ÓRBITA", "Y UN EMPUJÓN MÁS|HACIA LA LUNA"),
    S("El viaje duró tres días. Tres días flotando en una lata, mirando cómo la Tierra se hacía cada vez más chica.", 0.55,
      'viaje', "TRES DÍAS", "LA TIERRA CADA VEZ|MÁS CHIQUITA"),
    S("Hasta que la taparon con el pulgar. Todo lo que conocés, todos los que amás, detrás de un dedo.", 0.65,
      'viaje', "LA TAPARON|CON EL PULGAR", "TODO, DETRÁS|DE UN DEDO"),

    # ------------------------------------------------------------- EL DESCENSO
    S("20 de julio. Ármstrong y Óldrin pasan al módulo lunar. Lo bautizaron Águila. Cólins queda solo arriba.", 0.4,
      'aguila', "20 DE JULIO", "EL ÁGUILA|SE SEPARA"),
    S("Empieza el descenso. Y empiezan los problemas, uno atrás del otro.", 0.5,
      None, "EMPIEZA|EL DESCENSO", "Y LOS PROBLEMAS"),
    S("Primero, la señal de radio se corta y vuelve. La antena no está apuntando bien.", 0.45,
      'alarma', "SE CORTA|LA RADIO", "LA ANTENA NO|APUNTA BIEN"),
    S("Después ven que están pasando de largo los puntos de referencia. Van cuatro segundos adelantados.", 0.45,
      'alarma', "VAN ADELANTADOS", "CUATRO SEGUNDOS|DE MÁS"),
    S("Cuatro segundos, a esa velocidad, son varios kilómetros de error. Van a caer en un lugar que nadie estudió.", 0.55,
      'alarma', "VARIOS KILÓMETROS|DE ERROR", "EN UN LUGAR|NO ESTUDIADO"),
    S("Y a dos mil metros de altura, suena una alarma en la computadora: mil doscientos dos.", 0.5,
      'alarma', "ALARMA 1202", "A 2.000 METROS|DE ALTURA"),
    S("Nadie en la cabina sabe qué significa. Ármstrong pregunta a Jiúston, con la voz igual de tranquila que siempre.", 0.5,
      'alarma', "NADIE SABE|QUÉ ES", "«DENNOS UNA LECTURA|DEL 1202»"),
    S("En el control, un chico de veintiséis años llamado estiv  Beils lo reconoce en dos segundos.", 0.45,
      'control', "STEVE BALES|26 AÑOS", "LO RECONOCE EN|DOS SEGUNDOS"),
    S("La computadora está recibiendo más tareas de las que puede hacer. Pero no se cuelga.", 0.45,
      'computadora', "ESTÁ SATURADA", "PERO NO SE CUELGA"),
    S("Porque el programa de Márgaret Jámilton hace exactamente lo que ella peleó por incluir: tira lo que no es urgente, y sigue con lo importante.", 0.55,
      'hamilton', "EL PROGRAMA|DE HAMILTON", "TIRA LO QUE NO|ES URGENTE"),
    S("Beils dice una sola palabra: seguimos. Y siguen bajando.", 0.6,
      'control', "«GO»", "Y SIGUEN BAJANDO"),
    S("A quinientos metros, Ármstrong mira por la ventana y ve dónde los está llevando la computadora.", 0.45,
      'crateres', "500 METROS", "ARMSTRONG MIRA|POR LA VENTANA"),
    S("Un cráter del tamaño de una cancha de fútbol, rodeado de piedras del tamaño de un auto.", 0.5,
      'crateres', "UN CRÁTER", "Y PIEDRAS COMO|AUTOS"),
    S("Si bajan ahí, la nave se da vuelta, o rompe una pata. Y si rompen una pata, no vuelven nunca.", 0.55,
      'crateres', "SI BAJAN AHÍ", "NO VUELVEN NUNCA"),
    S("Ármstrong toma el control manual. Se convierte, literalmente, en el piloto de helicóptero más caro de la historia.", 0.5,
      'aguila', "CONTROL MANUAL", "EL PILOTO MÁS CARO|DE LA HISTORIA"),
    S("Vuela horizontal, buscando un lugar plano. El combustible baja.", 0.5,
      'combustible', "BUSCA UN LUGAR|PLANO", "Y EL COMBUSTIBLE|BAJA"),
    S("Sesenta segundos, avisa Jiúston. Eso significa: sesenta segundos y hay que abortar.", 0.5,
      'combustible', "«SESENTA|SEGUNDOS»", "O HAY QUE ABORTAR"),
    S("En el control de misión ya nadie respira. Están mirando morir a dos personas en vivo, o verlas aterrizar.", 0.55,
      'control', "NADIE RESPIRA", "EN EL CONTROL|DE MISIÓN"),
    S("Treinta segundos, avisa Jiúston. Y Ármstrong sigue sin decir una palabra.", 0.55,
      'combustible', "«TREINTA|SEGUNDOS»", "Y ÉL NO DICE NADA"),
    S("El polvo lunar empieza a levantarse alrededor. Ya no ve el suelo: ve una nube gris moviéndose.", 0.5,
      'polvo', "SE LEVANTA|EL POLVO", "YA NO VE EL SUELO"),
    S("Luz de contacto. Una de las patas tocó. Motor apagado.", 0.5,
      'contacto', "LUZ DE CONTACTO", "MOTOR APAGADO"),
    S("Y entonces se escucha la frase: Jiúston, aquí Base Tranquilidad. El Águila ha alunizado.", 0.7,
      'aguila', "«AQUÍ BASE|TRANQUILIDAD»", "«EL ÁGUILA|HA ALUNIZADO»"),
    S("En el control, alguien responde con la voz temblando: nos estábamos poniendo azules; ya volvemos a respirar.", 0.6,
      'control', "«NOS ESTÁBAMOS|PONIENDO AZULES»", "«YA RESPIRAMOS»"),
    S("Les quedaba combustible para unos veinte segundos más de vuelo. Veinte segundos.", 0.65,
      'combustible', "LES QUEDABAN", "20 SEGUNDOS|DE COMBUSTIBLE"),

    # ---------------------------------------------------------------- EL PASO
    S("El plan decía que ahora tenían que dormir. Nadie durmió, obviamente.", 0.45,
      None, "EL PLAN DECÍA|«DORMIR»", "NADIE DURMIÓ"),
    S("Antes de salir, Óldrin hizo algo que casi nadie sabe: sacó pan y vino, y comulgó en silencio.", 0.55,
      'comunion', "ALDRIN SACÓ|PAN Y VINO", "Y COMULGÓ|EN SILENCIO"),
    S("Seis horas y media después del alunizaje, se abrió la escotilla.", 0.45,
      'escotilla2', "SEIS HORAS|Y MEDIA", "SE ABRE LA|ESCOTILLA"),
    S("Ármstrong bajó la escalera despacio. Probó el último escalón dos veces, por si el polvo se hundía.", 0.5,
      'escalera', "BAJA DESPACIO", "PRUEBA EL ÚLTIMO|ESCALÓN DOS VECES"),
    S("Y a las dos y cincuenta y seis de la madrugada, hora universal, apoyó la bota izquierda.", 0.5,
      'bota', "2:56 DE LA|MADRUGADA", "APOYA LA BOTA|IZQUIERDA"),
    S("Un pequeño paso para el hombre. Un salto gigante para la humanidad.", 0.75,
      'bota', "«UN PEQUEÑO|PASO»", "«UN SALTO GIGANTE|PARA LA HUMANIDAD»"),
    S("Seiscientos millones de personas lo estaban viendo. Una de cada cinco personas vivas en ese momento.", 0.55,
      'mundotv', "600 MILLONES|MIRANDO", "UNA DE CADA CINCO|PERSONAS VIVAS"),
    S("En Buenos Aires, en Tokio, en un pueblo sin luz eléctrica: todos mirando la misma imagen borrosa en blanco y negro.", 0.6,
      'mundotv', "EN TODO|EL MUNDO", "LA MISMA IMAGEN|BORROSA"),
    S("Veinte minutos después bajó Óldrin. Miró alrededor y dijo dos palabras perfectas: magnífica desolación.", 0.6,
      'aldrin', "BAJA ALDRIN", "«MAGNÍFICA|DESOLACIÓN»"),

    # ------------------------------------------------------------ EN LA LUNA
    S("Caminar ahí era raro. La gravedad es seis veces menor: descubrieron que lo más cómodo era ir a los saltitos.", 0.45,
      'saltos', "SEIS VECES|MENOS GRAVEDAD", "LO MÁS CÓMODO:|IR A SALTITOS"),
    S("El polvo se pegaba a todo, y adentro de la nave olía, según ellos, a pólvora quemada.", 0.5,
      'polvo', "EL POLVO|SE PEGA", "Y HUELE A|PÓLVORA QUEMADA"),
    S("Plantaron una bandera con un alambre adentro, porque sin viento se caía como un trapo.", 0.5,
      'bandera', "LA BANDERA", "LLEVA UN ALAMBRE:|NO HAY VIENTO"),
    S("Dejaron un espejo que todavía hoy se usa para medir con láser la distancia exacta a la Luna.", 0.5,
      'espejo', "DEJARON|UN ESPEJO", "HOY TODAVÍA|SE USA"),
    S("Dejaron una placa: vinimos en paz, en nombre de toda la humanidad.", 0.55,
      'placa', "UNA PLACA", "«VINIMOS EN PAZ|EN NOMBRE DE TODOS»"),
    S("Y dejaron medallas con los nombres de los muertos: Grísom, Uáit, Cháfi... y también Gagárin y Komarov.", 0.6,
      'medallas', "MEDALLAS CON|LOS MUERTOS", "TAMBIÉN LOS|SOVIÉTICOS"),
    S("Ahí arriba, por un rato, no hubo dos bandos. Hubo una sola lista de gente que no volvió.", 0.65,
      None, "NO HUBO|DOS BANDOS", "UNA SOLA LISTA|DE AUSENTES"),
    S("Recibieron un llamado del presidente Nícson desde Washintong. La llamada telefónica más larga de la historia.", 0.5,
      'llamada', "LLAMA NIXON", "LA LLAMADA MÁS|LARGA DE LA HISTORIA"),
    S("Mientras tanto, Cólins pasaba solo por detrás de la Luna, sin radio, sin nadie. La persona más aislada que existió jamás.", 0.6,
      'collins', "COLLINS,|SOLO", "LA PERSONA MÁS|AISLADA JAMÁS"),
    S("Él lo escribió después, y no sonaba triste: dijo que sentía no miedo, sino conciencia, expectativa y satisfacción.", 0.6,
      'collins', "NO SENTÍA MIEDO", "CONCIENCIA Y|SATISFACCIÓN"),

    # ------------------------------------------------------------- LA VUELTA
    S("Pero faltaba lo más peligroso, y casi nadie lo cuenta: había que despegar de la Luna.", 0.45,
      'despegue', "FALTABA|LO PEOR", "HABÍA QUE|DESPEGAR"),
    S("Y para eso había un solo motor. Sin repuesto. Sin plan B. Si no encendía, se quedaban ahí para siempre.", 0.6,
      'despegue', "UN SOLO MOTOR", "SIN REPUESTO|SIN PLAN B"),
    S("De hecho, ya estaba escrito el discurso por si eso pasaba. Se llamaba: en caso de desastre lunar.", 0.5,
      'discurso', "YA ESTABA ESCRITO|EL DISCURSO", "«EN CASO DE|DESASTRE LUNAR»"),
    S("Decía que esos hombres sabían que no había esperanza de rescate, pero sabían también que había esperanza para la humanidad.", 0.6,
      'discurso', "«SIN ESPERANZA|DE RESCATE»", "«PERO CON ESPERANZA|PARA TODOS»"),
    S("Nunca hizo falta leerlo. Antes de subir, Óldrin rompió sin querer con la mochila el interruptor del motor.", 0.5,
      'interruptor', "NUNCA SE LEYÓ", "PERO ROMPIERON|EL INTERRUPTOR"),
    S("Lo arreglaron metiendo en el agujero una lapicera. En serio. Volvieron de la Luna gracias a una lapicera.", 0.65,
      'interruptor', "LO ARREGLARON|CON UNA LAPICERA", "EN SERIO"),
    S("El motor encendió. Se encontraron con Cólins en órbita. Y volvieron a casa.", 0.5,
      'acople', "EL MOTOR|ENCENDIÓ", "SE ENCUENTRAN|CON COLLINS"),
    S("La reentrada fue a cuarenta mil kilómetros por hora, con el escudo térmico a dos mil ochocientos grados.", 0.5,
      'reentrada', "40.000 KM/H", "EL ESCUDO A|2.800 GRADOS"),
    S("El 24 de julio de 1969 cayeron en el Pacífico. Y apenas los subieron al barco... los encerraron veintiún días.", 0.55,
      'amerizaje', "24 JULIO 1969", "CAEN EN EL|PACÍFICO"),
    S("Por si traían algún germen lunar. Los tres hombres más famosos del planeta, en cuarentena, jugando a las cartas.", 0.65,
      'cuarentena', "21 DÍAS|EN CUARENTENA", "JUGANDO A|LAS CARTAS"),

    # ----------------------------------------------------------- LO QUE SIGUIÓ
    S("Después vinieron más. El Apolo 12 fue alcanzado por un rayo a los treinta y seis segundos del despegue.", 0.45,
      'rayo', "APOLO 12", "LO ALCANZA UN RAYO|A LOS 36 SEGUNDOS"),
    S("Se apagó medio tablero. Un ingeniero de veinticuatro años recordó un interruptor oscuro, y salvó la misión por radio.", 0.55,
      'rayo', "SE APAGA|MEDIO TABLERO", "UN CHICO DE 24|SALVA LA MISIÓN"),
    S("El Apolo 13 explotó camino a la Luna. Jiúston, tuvimos un problema.", 0.5,
      'apolo13', "APOLO 13", "«HOUSTON, TUVIMOS|UN PROBLEMA»"),
    S("Se quedaron sin oxígeno, sin luz y sin calefacción, a trescientos mil kilómetros de su casa.", 0.5,
      'apolo13', "SIN OXÍGENO|SIN LUZ", "A 300.000 KM|DE SU CASA"),
    S("Usaron el módulo lunar como bote salvavidas. Y en tierra armaron un filtro de aire con medias, cinta y cartón.", 0.55,
      'filtro', "UN FILTRO CON|CINTA Y CARTÓN", "Y VOLVIERON VIVOS"),
    S("Volvieron los tres vivos. Es, probablemente, el fracaso mejor resuelto de la historia de la ingeniería.", 0.6,
      'apolo13', "EL FRACASO MEJOR|RESUELTO", "DE LA HISTORIA"),
    S("Después hubo autos lunares, martillos de geólogo, y hasta un hombre que jugó al golf en la Luna.", 0.5,
      'rover', "AUTOS LUNARES", "Y HASTA GOLF|EN LA LUNA"),
    S("En diciembre de 1972, Yin Sernan subió la escalera del Apolo 17 y dijo que volveríamos pronto.", 0.5,
      'cernan', "DICIEMBRE 1972", "GENE CERNAN,|EL ÚLTIMO"),
    S("Fue el último ser humano en pisar la Luna. Hace más de cincuenta años que nadie vuelve.", 0.65,
      'cernan', "EL ÚLTIMO|EN PISARLA", "HACE MÁS DE|50 AÑOS"),

    # ----------------------------------------------------------- POR QUÉ FRENÓ
    S("¿Y por qué paramos? Por lo mismo que empezamos: porque nunca fue por la ciencia.", 0.5,
      None, "¿POR QUÉ|PARAMOS?", "PORQUE NUNCA FUE|POR LA CIENCIA"),
    S("Ganada la carrera, la gente se aburrió. Las últimas misiones ni siquiera se transmitían enteras por televisión.", 0.5,
      'aburrimiento', "GANADA LA|CARRERA", "LA GENTE|SE ABURRIÓ"),
    S("Cancelaron el Apolo 18, 19 y 20. Los cohetes que ya estaban construidos terminaron en un museo, acostados.", 0.6,
      'museo', "CANCELAN 18,|19 Y 20", "LOS COHETES|A UN MUSEO"),

    # ------------------------------------------------------------------ CIERRE
    S("Pero algo quedó. Y no es solo la tecnología, aunque de ahí salieron cosas que usás todos los días.", 0.45,
      None, "ALGO QUEDÓ", None),
    S("Quedó la prueba de que un montón de gente común, coordinada, puede hacer algo imposible en ocho años.", 0.55,
      'equipo', "GENTE COMÚN", "HACIENDO ALGO|IMPOSIBLE"),
    S("Allá arriba no hay viento, no hay lluvia, no hay nadie que barra. Las huellas siguen exactamente donde quedaron.", 0.55,
      'huella', "NO HAY VIENTO|NI LLUVIA", "LAS HUELLAS|SIGUEN AHÍ"),
    S("Van a seguir ahí millones de años. Mucho después de que no quede nada de nosotros.", 0.6,
      'huella', "VAN A DURAR", "MILLONES DE AÑOS"),
    S("Y todo eso empezó con tres tipos que murieron en una cápsula que ni siquiera despegó.", 0.6,
      'tripulacion', "Y TODO EMPEZÓ", "CON TRES QUE|NO DESPEGARON"),
    S("Así que esta noche, cuando salgas al patio y la mires... acordate de que ahí arriba hay huellas nuestras.", 0.55,
      'patio', "ESTA NOCHE,|MIRALA", "HAY HUELLAS|NUESTRAS"),
    S("La Luna dejó de ser inalcanzable el día que un grupo de personas decidió, en serio, ir a buscarla.", 0.8,
      'luna', "DEJÓ DE SER|INALCANZABLE", "EL DÍA QUE FUIMOS|A BUSCARLA"),
]
