"""Volumen 1 — segunda parte, guion pulido.

Cada escena trae:
  n        número de escena (continúa la numeración del guion original)
  sec      sección del documental
  voz      'D' narradora (Daniela) · 'X' citas (voz masculina)
  txt      texto de narración, con las palabras en inglés escritas
           como se pronuncian para que la voz sintética no se trabe
  rot      líneas del rótulo dibujado en pantalla
  color    acento del rótulo: R rojo · B azul · G dorado · I tinta
  img      nombre del dibujo en /mnt/documents/ref
"""

ESCENAS = [
    (10, 'EL PRECIO', 'D',
     'Navidad de mil novecientos sesenta y ocho. Tres hombres pasan la Nochebuena dando diez vueltas alrededor de la Luna, sin poder bajar. Miran el agujero por el que algún día va a entrar alguien, y siguen de largo.',
     ['NAVIDAD', 'DE 1968'], 'R', 'v3-apollo8'),
    (11, 'EL PRECIO', 'D',
     'Y en la cuarta vuelta, alguien grita: mirá eso. Por encima del horizonte gris asoma la Tierra, chiquita, azul, sola. Sacan una foto de apuro. Esa foto cambió la cabeza de una generación entera.',
     ['LA TIERRA', 'SALIENDO'], 'B', 'v3-earthrise'),
    (12, 'EL PRECIO', 'D',
     'Mayo del sesenta y nueve: el ensayo general. El Apolo diez baja hasta quince kilómetros del suelo lunar, tan cerca que ven piedras, y tiene orden de volverse. Quince kilómetros, y prohibido tocar.',
     ['A 15 KM', 'Y VOLVER'], 'G', 'v3b-apollo10'),
    (13, 'LOS TRES HOMBRES', 'D',
     'Ahora sí, ellos. Si te los cruzabas en la calle no los mirabas dos veces: tres tipos de camisa blanca, corte militar y cara de nada. Y eran, probablemente, los tres pilotos más fríos del planeta.',
     ['TRES PILOTOS', 'MUY FRÍOS'], 'B', 'v3-trio'),
    (14, 'LOS TRES HOMBRES', 'D',
     'Nil Ármstrong, treinta y ocho años, de Ohio. Callado hasta lo incómodo. Setenta y ocho misiones de combate en Corea, y después piloto del equis quince, un avión que raspaba el borde del espacio.',
     ['NEIL', 'ARMSTRONG'], 'B', 'v3-armstrong'),
    (15, 'LOS TRES HOMBRES', 'D',
     'En el Yéminis ocho su nave se puso a girar una vuelta por segundo. La vista se le iba en blanco. Apagó todo el sistema a mano, con los ojos nublados, y trajo la cápsula a casa. Tenía treinta y cinco años.',
     ['UNA VUELTA', 'POR SEGUNDO'], 'R', 'v3-gemini8'),
    (16, 'LOS TRES HOMBRES', 'D',
     'Un año antes de la Luna, entrenando en un armatoste al que le decían la cama voladora, se eyectó a menos de un segundo de estrellarse. El paracaídas se abrió casi rozando el pasto. Esa misma tarde volvió a la oficina a firmar papeles.',
     ['LA CAMA', 'VOLADORA'], 'I', 'v3b-camavoladora'),
    (17, 'LOS TRES HOMBRES', 'D',
     'Baz Áldrin, treinta y nueve, el opuesto exacto: hablador, competitivo, doctorado en encuentro orbital. En la oficina le decían doctor randevú, y no siempre era un elogio.',
     ['DOCTOR', 'RENDEZVOUS'], 'B', 'v3-aldrin'),
    (18, 'LOS TRES HOMBRES', 'D',
     'Y Máicol Cólins, treinta y ocho, nacido en Roma. El simpático, el que escribía bien, el irónico. Y el que se iba a quedar arriba, dando vueltas solo, mientras los otros dos se volvían inmortales.',
     ['EL QUE', 'SE QUEDA'], 'G', 'v3-collins'),
    (19, '16 DE JULIO DE 1969', 'D',
     'Amanece en Florida. Un millón de personas acampan en las rutas, en los techos de los autos, en la arena. Heladeras, chicos dormidos, señoras rezando el rosario. Nadie sabe si va a ver un despegue o una tragedia.',
     ['UN MILLÓN', 'DE PERSONAS'], 'R', 'v3-playas'),
    (20, '16 DE JULIO DE 1969', 'D',
     'Desayunan bife con huevos, se meten en trajes de más de treinta kilos, y una camioneta plateada los lleva a la plataforma treinta y nueve A. Van callados, con la valijita de oxígeno en la mano, como tres tipos yendo a trabajar.',
     ['TRAJES DE', '30 KILOS'], 'I', 'v3-trajes'),
    (21, '16 DE JULIO DE 1969', 'D',
     'Y ahí está la bestia. El Saturno cinco: ciento diez metros, un edificio de treinta y seis pisos, tres mil toneladas. El noventa por ciento de eso es combustible. Estás sentado arriba de una bomba con ventanas.',
     ['110 METROS', 'DE ALTURA'], 'B', 'v3b-saturno-torre'),
    (22, '16 DE JULIO DE 1969', 'D',
     'Abajo, cinco motores efe uno, todavía hoy los más potentes que voló un ser humano. Quemaban trece toneladas de combustible por segundo. Trece toneladas. Por segundo.',
     ['13 TONELADAS', 'POR SEGUNDO'], 'R', 'v3b-motoresf1'),
    (23, '16 DE JULIO DE 1969', 'D',
     'En la sala de control, chicos de veintipocos años con corbata finita miran pantallas verdes. Nueve. Ocho. Siete. Seis. Cinco. Cuatro. Tres. Dos. Uno. Cero.',
     ['NUEVE...', 'CERO'], 'R', 'v3b-cuentaatras'),
    (24, '16 DE JULIO DE 1969', 'D',
     'Una nube blanca se come la plataforma, y de adentro sale una llama de trescientos metros. El cohete no salta: se levanta despacio, como si dudara. Trece treinta y dos, hora universal.',
     ['UNA LLAMA', 'DE 300 M'], 'G', 'v3-despegue'),
    (25, '16 DE JULIO DE 1969', 'D',
     'En las playas, quince segundos de nada. El cohete ya sube y todavía no llegó el sonido. Y después llega: un golpe en el pecho que hace vibrar los vidrios, los dientes y el estómago. Muchos lloraron sin entender por qué.',
     ['15 SEGUNDOS', 'DE SILENCIO'], 'B', 'v3-sonido'),
    (26, '16 DE JULIO DE 1969', 'D',
     'Arriba se sentía como un tren descarrilando. Áldrin contó que la cabina se sacudía tanto que no podía leer los instrumentos. Doce segundos para librar la torre. Dos minutos cuarenta para soltar la primera etapa.',
     ['COMO UN TREN', 'DESCARRILANDO'], 'I', 'v3b-cabina-sacudida'),
    (27, '16 DE JULIO DE 1969', 'D',
     'Nueve minutos después están en órbita, a veintiocho mil kilómetros por hora. Nueve minutos: eso tarda un cohete en cambiarte de mundo. Adentro, silencio, lapiceras flotando y tres tipos sonriendo.',
     ['9 MINUTOS', 'A OTRO MUNDO'], 'R', 'v3b-orbita-tierra'),
    (28, 'CAMINO A LA LUNA', 'D',
     'Dan una vuelta y media revisando cada sistema. Y entonces Jiúston dice la frase mágica: Apolo once, habilitados para inyección translunar. En criollo: pueden irse. Encienden el motor seis minutos y salen disparados.',
     ['HABILITADOS', 'PARA IRSE'], 'B', 'v3-houston'),
    (29, 'CAMINO A LA LUNA', 'D',
     'Ahora una maniobra rarísima: la nave se separa, gira ciento ochenta grados y vuelve a acoplarse de nariz con el módulo lunar, que venía guardado como un juguete en su caja. Todo esto a treinta y ocho mil kilómetros por hora.',
     ['GIRAR 180°', 'Y ACOPLAR'], 'I', 'v3-acople'),
    (30, 'CAMINO A LA LUNA', 'D',
     'Ese módulo, el Ígol, era la nave más frágil jamás construida. En algunas partes la pared tenía el espesor de tres hojas de papel. Se perforaba con un destornillador si apoyabas mal la mano.',
     ['TRES HOJAS', 'DE PAPEL'], 'R', 'v3-eagle'),
    (31, 'CAMINO A LA LUNA', 'D',
     'Adentro no había asientos: los sacaron para ahorrar peso. Volaban parados, sujetos con cables elásticos, mirando por dos ventanitas triangulares del tamaño de una tostadora.',
     ['VOLABAN', 'PARADOS'], 'I', 'v3b-eagle-interior'),
    (32, 'CAMINO A LA LUNA', 'D',
     'Al segundo día la Tierra ya era una canica. Ármstrong estiró el pulgar contra la ventana y la tapó entera. Después dijo: no me sentí grande, me sentí muy, muy chiquito.',
     ['LA TIERRA', 'ERA UNA CANICA'], 'G', 'v3-canica'),
    (33, 'EN ÓRBITA LUNAR', 'D',
     'Al cuarto día la Luna deja de ser un dibujo del cielo y se convierte en un paisaje. Enorme, gris, picada de agujeros, tan cerca que les tapa toda la ventana. Cólins dijo que era imponente y bastante siniestra.',
     ['LES TAPA', 'EL CIELO'], 'B', 'v3-lunacerca'),
    (34, 'EN ÓRBITA LUNAR', 'D',
     'Para quedar en órbita hay que frenar con el motor exactamente seis minutos. Y hay que hacerlo detrás de la Luna, sin radio, sin Jiúston, sin nadie. Si el motor no arranca, se van al espacio para siempre. Si no se apaga, se estrellan.',
     ['FRENAR', 'A CIEGAS'], 'R', 'v3b-detras-luna'),
    (35, 'EN ÓRBITA LUNAR', 'D',
     'Treinta y tres minutos de silencio en la sala. La señal tenía que volver a un segundo exacto. Y volvió. Con la voz más aburrida del mundo, Ármstrong lee los números de la órbita. La sala explota en aplausos.',
     ['ÓRBITA LUNAR', 'CONFIRMADA'], 'B', 'v3b-sala-aplausos'),
    (36, 'EN ÓRBITA LUNAR', 'D',
     'Y ven la cara oculta con sus propios ojos, algo que nadie había hecho antes de mil novecientos sesenta y ocho. Cólins la describió así: un montón de arena de playa arruinada por chicos. No hay poesía ahí atrás.',
     ['LA CARA', 'OCULTA'], 'I', 'v3-desolacion'),
    (37, 'EL DESCENSO', 'D',
     'Veinte de julio. Ármstrong y Áldrin se meten en el Ígol y cierran la escotilla. Cólins les dice: cuídense allá abajo. Ármstrong contesta: nos vemos a la vuelta. Y el módulo se suelta.',
     ['ESCOTILLA', 'CERRADA'], 'R', 'v3b-escotilla-eagle'),
    (38, 'EL DESCENSO', 'D',
     'Cólins queda solo. Cada vez que pasa por detrás de la Luna se convierte en el ser humano más aislado que existió: ni una onda de radio lo alcanza. Tres mil millones de personas de un lado, y él del otro.',
     ['EL MÁS SOLO', 'DE LA HISTORIA'], 'B', 'v3-solo'),
    (39, 'EL DESCENSO', 'X',
     'Él lo escribió así: no siento miedo ni soledad. Siento conciencia, expectativa, satisfacción, casi júbilo.',
     ['«CASI', 'JÚBILO»'], 'G', 'v3b-collins-ventana'),
    (40, 'EL DESCENSO', 'D',
     'Pero tenía un terror concreto, anotado en su libreta: volver solo. A las veinte cero cinco el Ígol enciende el motor y empieza lo que la NASA llamó, sin una gota de emoción, descenso motorizado. Doce minutos.',
     ['DESCENSO', 'MOTORIZADO'], 'R', 'v3b-descenso'),
    (41, 'EL DESCENSO', 'D',
     'Bajan de espaldas al suelo, frenando. Ármstrong mira pasar el cráter Máskelin por la ventana, cuenta los segundos de cabeza como quien mide una cuadra, y le da mal.',
     ['LA CUENTA', 'DA MAL'], 'I', 'v3b-crater-maskelyne'),
    (42, 'EL DESCENSO', 'D',
     'Van dos o tres segundos adelantados. Dicho así no es nada. A esa velocidad son varios kilómetros de más. Traducción: no van a caer donde estudiaron. Van a caer en un lugar que nadie miró en un mapa.',
     ['VARIOS KM', 'DE MÁS'], 'R', 'v3b-trayectoria'),
    (43, 'EL DESCENSO', 'D',
     'Y a mil ochocientos metros, la computadora hace lo peor que puede hacer una computadora: se queja. Alarma de programa, mil doscientos dos. Ármstrong lo dice con una calma que da escalofríos, y pregunta por una lectura.',
     ['ALARMA', '1202'], 'R', 'v3-alarma'),
    (44, 'EL DESCENSO', 'D',
     'En Jiúston la decisión cae sobre Stiv Béils, veintiséis años, encargado de guiado. Nadie más puede decidirlo. Y él nunca vio esa alarma en un vuelo real.',
     ['STEVE BALES', '26 AÑOS'], 'B', 'v3-bales'),
    (45, 'EL DESCENSO', 'D',
     'Por el auricular lo respalda Yak Gárman, un programador de veinticuatro años que había hecho a mano una lista de todas las alarmas posibles. Cuatro segundos de silencio. Y Béils grita: adelante.',
     ['CUATRO', 'SEGUNDOS'], 'R', 'v3b-garman'),
    (46, 'EL DESCENSO', 'D',
     'Porque esa computadora estaba diseñada para no colgarse nunca. Cuando se saturaba, tiraba por la ventana las tareas menos importantes, se reiniciaba sola en un segundo y seguía calculando lo único que importaba: no chocar.',
     ['NO SE COLGABA:', 'PRIORIZABA'], 'B', 'v3b-agc-prioridad'),
    (47, 'EL DESCENSO', 'D',
     'Ese programa lo dirigió Mágaret Jámilton, treinta y dos años, que los fines de semana llevaba a su hija chiquita al laboratorio y la sentaba a dibujar mientras ella escribía el código que salvó el alunizaje.',
     ['MARGARET', 'HAMILTON'], 'G', 'v3-hamilton'),
    (48, 'EL DESCENSO', 'D',
     'Dos mil metros. Suena otra alarma, la mil doscientos uno, prima hermana de la anterior. Esta vez Jiúston no duda ni un segundo: adelante, misma alarma. Y siguen bajando.',
     ['ALARMA 1201:', 'ADELANTE'], 'R', 'v3b-alarma1201'),
    (49, 'EL DESCENSO', 'D',
     'Áldrin canta números sin parar, como un metrónomo: setecientos cincuenta pies, bajando a veintitrés. Es su única tarea, y de esa voz depende que Ármstrong no tenga que mirar el tablero.',
     ['750 PIES,', 'BAJANDO'], 'I', 'v3b-aldrin-numeros'),
    (50, 'EL DESCENSO', 'D',
     'Y Ármstrong mira por la ventana y ve algo que no le gusta nada: la computadora los lleva derecho al borde de un cráter, y el borde está tapado de rocas del tamaño de un auto.',
     ['ROCAS COMO', 'AUTOS'], 'R', 'v3-rocas'),
    (51, 'EL DESCENSO', 'D',
     'Entonces hace lo que no estaba en ningún manual: toma el control a mano y se pone a volar por encima del campo de rocas, buscando un pedazo de suelo liso. Como quien da vueltas buscando dónde estacionar. Con el tanque casi vacío.',
     ['CONTROL', 'MANUAL'], 'B', 'v3b-manual'),
    (52, 'EL DESCENSO', 'D',
     'En Jiúston no saben nada de esto. No hay cámara, no hay imagen, no hay explicación. Solo escuchan la voz de Áldrin cantando números que bajan, y a Ármstrong que no dice absolutamente nada.',
     ['SIN VIDEO:', 'SOLO NÚMEROS'], 'I', 'v3-houston'),
    (53, 'EL DESCENSO', 'D',
     'Se prende la luz de combustible bajo. Bob Cárlton empieza a contar en voz alta lo que queda: sesenta segundos. Después de eso, o tocan el suelo, o abortan y se vuelven.',
     ['60', 'SEGUNDOS'], 'R', 'v3-combustible'),
    (54, 'EL DESCENSO', 'D',
     'Ármstrong no contesta. No dice una palabra. Sigue volando, corriéndose hacia la izquierda, y encuentra un claro entre las rocas del tamaño de una cancha de fútbol. Empieza a bajar los últimos treinta metros.',
     ['ENCUENTRA', 'UN CLARO'], 'B', 'v3b-claro'),
    (55, 'EL DESCENSO', 'D',
     'Y aparece un problema que nadie previó: el polvo. Sin aire no hay remolinos, así que corre en línea recta y plana, como una sábana que alguien tira sobre el piso. Ármstrong pierde la referencia de la altura.',
     ['POLVO SIN', 'REMOLINOS'], 'G', 'v3-polvo'),
    (56, 'EL DESCENSO', 'D',
     'Treinta segundos. Chárli Diuk lo dice y después contó: teníamos un montón de tipos acá abajo a punto de ponerse azules. Se habían olvidado de respirar.',
     ['30 SEGUNDOS:', 'NADIE RESPIRA'], 'R', 'v3b-duke'),
    (57, 'EL DESCENSO', 'D',
     'Y entonces una varilla de metro y medio que colgaba de una pata roza el suelo, y se prende una luz azul en el tablero. Áldrin dice tres palabras: luz de contacto.',
     ['LUZ DE', 'CONTACTO'], 'B', 'v3b-luz-contacto'),
    (58, 'EL DESCENSO', 'D',
     'Ármstrong apaga el motor. La nave cae el último metro y se apoya suave, casi con delicadeza. Veinte de julio de mil novecientos sesenta y nueve. Veinte horas, diecisiete minutos, cuarenta segundos.',
     ['20:17:40'], 'I', 'v3-alunizado'),
    (59, 'EL DESCENSO', 'D',
     'Quedaba entre veinticinco y cincuenta segundos de combustible. Menos de un minuto de margen entre el momento más glorioso del siglo veinte y dos muertos en el polvo.',
     ['QUEDABAN', '25 SEGUNDOS'], 'R', 'v3b-tanque-vacio'),
    (60, 'EL DESCENSO', 'X',
     'Un segundo de silencio. Y después: Jiúston, aquí Base Tranquilidad. El Águila ha alunizado.',
     ['«EL ÁGUILA HA', 'ALUNIZADO»'], 'R', 'v3b-base-tranquilidad'),
    (61, 'EL DESCENSO', 'X',
     'Diuk le contesta trabado de puro nervio: copiado, Tranquilidad. Un montón de tipos acá estaban a punto de ponerse azules. Ya volvemos a respirar.',
     ['«YA VOLVEMOS', 'A RESPIRAR»'], 'B', 'v3b-sala-festejo'),
    (62, 'EL DESCENSO', 'D',
     'La sala estalla. Hay un controlador que rompió el lápiz que tenía en la mano y no se dio cuenta hasta el día siguiente. La edad promedio de esa sala, esa noche, era veintiséis años.',
     ['EDAD PROMEDIO:', '26 AÑOS'], 'G', 'v3b-lapiz-roto'),
    (63, 'EL DESCENSO', 'D',
     'Y del otro lado del mundo, seiscientos millones de personas mirando un televisor en blanco y negro. En los bares, en las veredas, en las vidrieras de las tiendas. La audiencia más grande que tuvo nunca nada.',
     ['600 MILLONES', 'MIRANDO'], 'R', 'v3b-televisores'),
    (64, 'LAS SEIS HORAS MÁS RARAS', 'D',
     'Y lo primero que hacen no es festejar ni salir corriendo a caminar. Es dejar la nave lista para escapar, por si el suelo se hundía o perdían presión. Dos horas de preparativos de fuga antes de mirar por la ventana.',
     ['DOS HORAS', 'POR SI HAY', 'QUE HUIR'], 'I', 'v3b-checklist'),
    (65, 'LAS SEIS HORAS MÁS RARAS', 'D',
     'Después Áldrin pide unos minutos de silencio en la radio, saca un cáliz del tamaño de un dedal, pan y vino, y toma la comunión. En la sexta parte de gravedad, el vino subió por la copa despacio. Fue el primer alimento consumido en otro mundo.',
     ['PAN Y VINO', 'EN LA LUNA'], 'G', 'v3b-comunion'),
    (66, 'LAS SEIS HORAS MÁS RARAS', 'D',
     'Mientras tanto, en la Tierra, había un discurso guardado en un cajón de la Casa Blanca. Lo escribió Uíliam Sáfair para Níckson y se titulaba: en caso de desastre lunar.',
     ['«EN CASO DE', 'DESASTRE LUNAR»'], 'I', 'v3b-discurso-nixon'),
    (67, 'LAS SEIS HORAS MÁS RARAS', 'X',
     'Empezaba así: el destino ha ordenado que los hombres que fueron a la Luna a explorar en paz, se queden en la Luna a descansar en paz.',
     ['«DESCANSAR', 'EN PAZ»'], 'R', 'v3b-safire-papel'),
    (68, 'LAS SEIS HORAS MÁS RARAS', 'D',
     'Ponerse los trajes les llevó tres horas. Tres. En un espacio del tamaño de dos cabinas de teléfono, con el otro adentro. Áldrin dijo que fue como cambiarse dentro de un placard, con un tipo que también se está cambiando.',
     ['TRES HORAS', 'EN UN PLACARD'], 'I', 'v3b-vestirse'),
    (69, 'EL PRIMER PASO', 'D',
     'Despresurizan y abren la escotilla: chiquita, cuadrada, pensada por ingenieros que no calcularon bien la mochila. Ármstrong sale de espaldas, gateando, mientras Áldrin le indica de qué lado moverse para no engancharse.',
     ['SALE DE', 'ESPALDAS'], 'B', 'v3b-escotilla-salida'),
    (70, 'EL PRIMER PASO', 'D',
     'Baja nueve escalones y en el último se detiene. Antes de pisar, prueba saltar hacia arriba, para asegurarse de que con ese traje iba a poder volver a subir. Pudo. Recién entonces bajó la bota.',
     ['NUEVE', 'ESCALONES'], 'I', 'v3b-escalera'),
    (71, 'EL PRIMER PASO', 'D',
     'Dos horas, cincuenta y seis minutos del veintiuno de julio de mil novecientos sesenta y nueve. La suela de una bota se apoya en el polvo de otro mundo, y se hunde un centímetro y medio.',
     ['21 DE JULIO', '02:56'], 'G', 'v3-primerpaso'),
    (72, 'EL PRIMER PASO', 'X',
     'Es un pequeño paso para el hombre, un gran salto para la humanidad.',
     ['«UN PEQUEÑO', 'PASO»'], 'R', 'v3b-huella-primera'),
    (73, 'EL PRIMER PASO', 'D',
     'Él juró toda la vida que dijo para un hombre, y que la radio se comió el un. Y lo primero que hizo después de la frase más famosa del siglo fue mucho menos poético: juntar tierra a manotazos y guardársela en el bolsillo del muslo, por si tenían que salir corriendo.',
     ['TIERRA EN', 'EL BOLSILLO'], 'I', 'v3b-bolsillo'),
    (74, 'EL PRIMER PASO', 'D',
     'Veinte minutos después baja Áldrin. Mira alrededor, ve un desierto sin aire, sin sonido y sin horizonte conocido, y suelta la segunda frase más famosa de la noche: magnífica desolación.',
     ['«MAGNÍFICA', 'DESOLACIÓN»'], 'B', 'v3b-aldrin-superficie'),
    (75, 'EN LA SUPERFICIE', 'D',
     'Caminar era rarísimo. El cuerpo pesa la sexta parte, pero la mochila conserva toda su inercia: si arrancabas, seguías. Probaron caminar normal, se tropezaron, y terminaron inventando un trotecito de canguro.',
     ['TROTE DE', 'CANGURO'], 'G', 'v3-canguro'),
    (76, 'EN LA SUPERFICIE', 'D',
     'Y la Luna tiene olor. Al sacarse los cascos, adentro del módulo, sintieron algo fuerte y metálico. Ármstrong dijo que olía a cenizas mojadas. Áldrin, a pólvora quemada.',
     ['OLOR A', 'PÓLVORA'], 'I', 'v3b-casco-olor'),
    (77, 'EN LA SUPERFICIE', 'D',
     'Clavar la bandera fue un papelón. Quince centímetros abajo el suelo era piedra: el mástil no entraba. Quedó apenas apoyada, y los dos rezaron para que no se cayera en vivo, frente a seiscientos millones de personas.',
     ['LA BANDERA', 'APENAS', 'APOYADA'], 'R', 'v3-bandera'),
    (78, 'EN LA SUPERFICIE', 'D',
     'Y al despegar, el chorro del motor la volteó igual. Áldrin la vio caer por la ventana y no se lo contó a nadie por años. Lleva medio siglo tirada en el polvo, probablemente ya blanca por la radiación.',
     ['LA VIO CAER', 'POR LA VENTANA'], 'I', 'v3b-bandera-caida'),
    (79, 'EN LA SUPERFICIE', 'D',
     'Los llamó Níckson por teléfono: la llamada de larga distancia más larga de la historia. Ármstrong, tieso como un poste, contestó como si estuviera dando un parte militar. Nadie le enseñó a improvisar en la Luna.',
     ['LA LLAMADA', 'MÁS LARGA'], 'B', 'v3b-telefono'),
    (80, 'EN LA SUPERFICIE', 'D',
     'Instalaron un sismómetro tan sensible que registró los pasos de Áldrin. Y descubrieron algo hermoso: cuando la golpeás, la Luna suena como una campana, y sigue vibrando casi una hora.',
     ['SUENA COMO', 'UNA CAMPANA'], 'G', 'v3b-sismometro'),
    (81, 'EN LA SUPERFICIE', 'D',
     'Dejaron también un panel de espejos que sigue funcionando hoy, cincuenta y siete años después. Todavía le disparamos láser y nos rebota. Gracias a eso sabemos que la Luna se aleja tres centímetros y medio por año.',
     ['3,5 CM', 'POR AÑO'], 'B', 'v3-reflector'),
    (82, 'EN LA SUPERFICIE', 'D',
     'Y dejaron una placa de acero atornillada a la pata: aquí, hombres del planeta Tierra pusieron pie por primera vez en la Luna. Vinimos en paz, en nombre de toda la humanidad.',
     ['«VINIMOS', 'EN PAZ»'], 'R', 'v3b-placa'),
    (83, 'EN LA SUPERFICIE', 'D',
     'Juntaron veintiún kilos de rocas en dos horas y media, apurados, con una pinza porque no podían agacharse. Ármstrong se alejó como mucho sesenta metros del módulo. Ese fue todo el radio del primer viaje: media cuadra.',
     ['21 KILOS', 'DE ROCAS'], 'I', 'v3b-bolsa-rocas'),
    (84, 'EN LA SUPERFICIE', 'D',
     'Y antes de cerrar tiraron afuera todo lo que pesaba y ya no servía: mochilas, botas, herramientas, cámaras y las bolsas de desechos humanos. Sí: hay noventa y seis bolsas de eso en la Luna. Es parte del monumento.',
     ['96 BOLSAS', 'EN LA LUNA'], 'G', 'v3b-basura-lunar'),
    (85, 'VOLVER', 'D',
     'Duermen mal, con frío, con la luz entrando por las ventanas. Y al despertarse Áldrin ve algo en el piso: un pedacito de plástico negro. Es la palanca del interruptor que enciende el motor de ascenso. La rompieron con la mochila.',
     ['LA PALANCA', 'ROTA'], 'R', 'v3b-interruptor-roto'),
    (86, 'VOLVER', 'D',
     'Sin ese interruptor no hay despegue. Y estaban a trescientos ochenta mil kilómetros de la ferretería más cercana, con doscientos cincuenta mil dólares de equipo alrededor y ninguna herramienta que sirviera.',
     ['380.000 KM', 'SIN FERRETERÍA'], 'I', 'v3-lapicera'),
    (87, 'VOLVER', 'D',
     'Entonces Áldrin saca del bolsillo una lapicera de fibra, mete la punta de plástico en el agujero y empuja. Clic. Funcionó. La vuelta de la Luna terminó dependiendo de un marcador.',
     ['CLIC.', 'FUNCIONÓ'], 'R', 'v3b-clic'),
    (88, 'VOLVER', 'D',
     'Diecisiete cincuenta y cuatro. La mitad de arriba del Ígol se separa de la de abajo, que queda ahí para siempre convertida en plataforma de lanzamiento, y sube en línea recta. Sin cuenta regresiva, sin público.',
     ['17:54', 'DESPEGUE'], 'B', 'v3-despegue-lunar'),
    (89, 'VOLVER', 'D',
     'Tres horas y media después se reencuentran con Cólins. Él tenía planeado darles un beso en la frente a cada uno. En el momento se contuvo, y les dio la mano. Dijo que se arrepintió toda la vida.',
     ['UN APRETÓN', 'DE MANOS'], 'I', 'v3b-reencuentro'),
    (90, 'VOLVER', 'D',
     'Vuelven cubiertos de polvo gris hasta las pestañas, y meten ese olor raro adentro de la nave. Cólins escribió que el olor a Luna los acompañó los tres días de vuelta a casa.',
     ['EL OLOR', 'VOLVIÓ', 'CON ELLOS'], 'G', 'v3b-polvo-cabina'),
    (91, 'VOLVER', 'D',
     'Caen en el Pacífico tres días después. La cápsula entra a cuarenta mil kilómetros por hora y el escudo llega a tres mil grados: una bola de fuego que se ve desde el barco. Y flota. Y se abren tres paracaídas naranjas.',
     ['UNA BOLA', 'DE FUEGO'], 'R', 'v3-splashdown'),
    (92, 'VOLVER', 'D',
     'Y acá viene lo delirante: cuarentena de veintiún días. Nadie podía jurar que no hubieran traído un microbio lunar. Al plan lo apodaban, con humor negro, el miedo a los cereales: por si un bicho arruinaba las cosechas del planeta.',
     ['EL MIEDO A', 'LOS CEREALES'], 'I', 'v3b-cuarentena-cereal'),
    (93, 'VOLVER', 'D',
     'Los encerraron en un tráiler Érstrim con sillones y cenicero, y Níckson los saludó por una ventanita como si fueran un acuario. Después de conquistar la Luna, los guardaron tres semanas en una casilla rodante.',
     ['UNA CASILLA', 'RODANTE'], 'B', 'v3-cuarentena'),
    (94, 'LO QUE QUEDÓ', 'D',
     'En el programa Apolo trabajaron cuatrocientas mil personas. Entre ellas, costureras que cosían los trajes a mano, capa por capa, con tolerancia de menos de un milímetro. Muchas venían de fabricar corsés y sostenes.',
     ['400.000', 'PERSONAS'], 'B', 'v3-costureras'),
    (95, 'LO QUE QUEDÓ', 'D',
     'Costó veinticinco mil millones de dólares de la época: más de doscientos mil millones de hoy. Y hubo gente que dijo, con toda la razón, que con esa plata se podía haber dado de comer a mucha gente acá abajo.',
     ['25.000', 'MILLONES'], 'R', 'v3b-presupuesto'),
    (96, 'LO QUE QUEDÓ', 'D',
     'Yil Scot Héron escribió una canción furiosa que se llamaba Un blanco en la Luna. Contaba que a su hermana la había mordido una rata mientras la televisión festejaba el cohete. Eso también es parte de esta historia.',
     ['UN BLANCO', 'EN LA LUNA'], 'I', 'v3b-scott-heron'),
    (97, 'LO QUE QUEDÓ', 'D',
     'Doce personas caminaron sobre la Luna, todas entre mil novecientos sesenta y nueve y mil novecientos setenta y dos. Doce. Y después nadie más. Hace más de medio siglo que ningún ser humano pisa otro mundo.',
     ['DOCE PERSONAS', 'Y NADIE MÁS'], 'R', 'v3b-doce-huellas'),
    (98, 'LO QUE QUEDÓ', 'D',
     'Las huellas siguen ahí, intactas. No hay viento ni lluvia que las borre. La de Ármstrong va a seguir dibujada millones de años, hasta que los micrometeoritos la desarmen grano por grano.',
     ['MILLONES', 'DE AÑOS'], 'G', 'v3-huella-final'),
    (99, 'LO QUE QUEDÓ', 'D',
     'Ármstrong volvió, dejó de dar entrevistas y se hizo profesor de ingeniería en una universidad chica. Cuando lo llamaban héroe se incomodaba. Decía que era un nerd de la ingeniería con medias blancas.',
     ['PROFESOR DE', 'INGENIERÍA'], 'B', 'v3b-armstrong-profesor'),
    (100, 'LO QUE QUEDÓ', 'D',
     'Cólins escribió el mejor libro que existe sobre volar al espacio, y repitió toda su vida que no se sintió solo allá arriba, sino parte de algo enorme. Murió en dos mil veintiuno.',
     ['EL MEJOR', 'LIBRO'], 'I', 'v3b-collins-libro'),
    (101, 'LO QUE QUEDÓ', 'D',
     'Áldrin volvió a la Tierra y se cayó a pedazos: depresión y alcoholismo. Lo contó en público cuando nadie hablaba de eso, y se recuperó. A los ochenta y dos años le pegó una piña a un tipo que le dijo mentiroso en la cara.',
     ['SE RECUPERÓ', 'Y LO CONTÓ'], 'B', 'v3b-aldrin-mayor'),
    (102, 'LO QUE QUEDÓ', 'D',
     'Y esa computadora que casi arruina todo tenía cuatro kilobytes de memoria. El teléfono que tenés en el bolsillo es millones de veces más potente, y lo usás para mirar videos de gatos. Con cuatro kilobytes llegaron a la Luna.',
     ['CUATRO', 'KILOBYTES'], 'R', 'v3b-agc-vs-telefono'),
    (103, 'LO QUE QUEDÓ', 'D',
     'Así que la próxima vez que salgas al patio y mires para arriba, acordate de esto: no es solo una piedra gris colgada del cielo. Es el único otro lugar del universo donde hay huellas humanas.',
     ['MIRÁ', 'PARA ARRIBA'], 'G', 'v3b-patio-noche'),
    (104, 'LO QUE QUEDÓ', 'D',
     'Hay una bandera caída, tres paneles de espejos que todavía nos contestan y una placa que dice que vinimos en paz. Están ahí arriba ahora mismo, mientras escuchás esto.',
     ['ESTÁN AHÍ', 'AHORA MISMO'], 'B', 'v3b-luna-objetos'),
    (105, 'LO QUE QUEDÓ', 'D',
     'Y todo eso lo hicieron unos tipos con reglas de cálculo, café frío, corbatas finitas y una lapicera de fibra que salvó el día.',
     ['REGLAS DE CÁLCULO', 'Y UNA LAPICERA'], 'R', 'v3b-reglas-calculo'),
]

PAUSAS_LARGAS = {12, 18, 27, 36, 63, 68, 74, 84, 93, 105}
