"""EL TITANIC — parte 2: la partida, el viaje, los avisos de hielo y el choque."""

from titanic_parte1 import _e

ESCENAS = [
    # ---------- SOUTHAMPTON ----------
    _e("Diez de abril de mil novecientos doce. Puerto de Sautámpton, Inglaterra. Mediodía.",
       ["10 DE ABRIL"], ["SOUTHAMPTON"], "t061",
       "a crowded dock with a huge liner moored and people boarding"),
    _e("El Titánic estaba amarrado y parecía imposible de creer. La gente se sacaba el sombrero para poder mirar hasta arriba.",
       ["IMPOSIBLE"], ["DE ABARCAR", "CON LA VISTA"], "t062",
       "people on a dock looking up at an enormous ship side"),
    _e("Al mando iba Édward Smiz, el capitán más respetado de la compañía. Sesenta y dos años y cuarenta de mar.",
       ["CAPITAN", "SMITH"], ["40 AÑOS", "DE MAR"], "t063",
       "a bearded ship captain in uniform with a white beard"),
    _e("Era su último viaje antes de jubilarse. Lo llamaban el capitán de los millonarios, porque todos querían viajar con él.",
       ["SU ULTIMO", "VIAJE"], ["ANTES DE", "JUBILARSE"], "t064",
       "a captain shaking hands with wealthy passengers on deck"),
    _e("Años antes había dicho una frase que después lo perseguiría: nunca vi un accidente digno de mención.",
       ["UNA FRASE"], ["QUE LO", "PERSEGUIRIA"], "t065",
       "a captain speaking to reporters with notebooks"),
    _e("A bordo también viajaba Tomas Ándrius, el ingeniero que había diseñado el barco. Iba anotando mejoras en una libreta.",
       ["THOMAS", "ANDREWS"], ["EL QUE LO", "DISEÑO"], "t066",
       "an engineer walking a ship corridor writing in a notebook"),
    _e("Y también Brus Ísmey, el dueño de la naviera, en la mejor suite del barco.",
       ["BRUCE ISMAY"], ["EL DUEÑO", "A BORDO"], "t067",
       "a well dressed man standing at the door of a luxury suite"),
    _e("A las doce en punto sonaron las sirenas y el barco empezó a moverse. Y casi choca antes de salir del puerto.",
       ["ZARPA"], ["Y CASI CHOCA"], "t068",
       "a giant liner slowly leaving a dock with tugboats"),
    _e("Al pasar, el desplazamiento de agua rompió las amarras de otro barco, el Nueva York, que giró hacia el Titánic.",
       ["ROMPE LAS", "AMARRAS"], ["DEL NEW YORK"], "t069",
       "a moored ship swinging loose toward a passing liner, ropes snapping"),
    _e("Quedaron a poco más de un metro de golpearse. Un remolcador lo evitó en el último segundo.",
       ["A UN METRO"], ["DEL CHOQUE"], "t070",
       "two ship hulls almost touching with a tugboat pushing between them"),
    _e("Varios pasajeros lo tomaron como un mal presagio. Uno bajó del barco en la escala siguiente.",
       ["MAL", "PRESAGIO"], ["ALGUNOS SE", "BAJARON"], "t071",
       "a passenger with a suitcase walking down a gangway alone"),
    _e("Esa tarde cruzaron el canal hasta Cherburgo, en Francia, a buscar más pasajeros.",
       ["CHERBURGO"], ["MAS PASAJEROS"], "t072",
       "small tender boats ferrying passengers to a big ship at dusk"),
    _e("Ahí subieron los apellidos más ricos del mundo. Entre ellos, Yon Yácob Ástor, el hombre más adinerado a bordo.",
       ["SUBEN LOS", "MAS RICOS"], ["JOHN JACOB", "ASTOR"], "t073",
       "an elegant couple in furs boarding a ship at night"),
    _e("Ástor tenía cuarenta y siete años y volvía a casa con su esposa de dieciocho, embarazada de cinco meses.",
       ["ASTOR"], ["Y SU JOVEN", "ESPOSA"], "t074",
       "a wealthy older man and a young pregnant woman on deck"),
    _e("También subió Benyamín Gúguenjaim, magnate del acero, con su valet y su amante. Su esposa quedó en Nueva York.",
       ["GUGGENHEIM"], ["MAGNATE", "DEL ACERO"], "t075",
       "a well dressed magnate with a servant carrying luggage"),
    _e("Y Moli Braun, millonaria, deslenguada y odiada por la alta sociedad. Anotala: va a reaparecer.",
       ["MOLLY BROWN"], ["RECORDA", "ESE NOMBRE"], "t076",
       "a confident woman in a large hat laughing among stiff aristocrats"),
    _e("Al día siguiente pararon en Kuinstaun, Irlanda, la última escala. Ahí subieron sobre todo emigrantes.",
       ["QUEENSTOWN"], ["ULTIMA", "ESCALA"], "t077",
       "irish emigrants with bundles boarding a tender boat"),
    _e("Un fogonero se asomó por lo alto de una chimenea apagada, con la cara negra de hollín, para mirar la costa.",
       ["UN FOGONERO"], ["EN LA", "CHIMENEA"], "t078",
       "a soot covered stoker peering out of the top of a ship funnel"),
    _e("Varios pasajeros lo vieron y se asustaron: parecía una figura negra saliendo del barco. Otro presagio, dijeron.",
       ["OTRO", "PRESAGIO"], ["DIJERON", "LOS PASAJEROS"], "t079",
       "passengers pointing up at a dark figure on a funnel"),
    _e("A la una y media de la tarde, el Titánic puso rumbo al oeste. Nunca más tocaría tierra.",
       ["RUMBO OESTE"], ["NUNCA MAS", "TOCARIA TIERRA"], "t080",
       "a liner sailing away into open ocean seen from the coast"),

    # ---------- LA VIDA A BORDO ----------
    _e("Los primeros días fueron perfectos. Mar planchado, sol y un barco que casi no se movía.",
       ["DIAS", "PERFECTOS"], ["MAR PLANCHADO"], "t081",
       "a calm flat ocean with a liner sailing under the sun"),
    _e("En primera clase se comía en once tiempos. Ostras, cordero, pato, helado y champán.",
       ["11 PLATOS"], ["POR CENA"], "t082",
       "an elaborate dinner table with many plates and glasses"),
    _e("En tercera clase la comida era simple, pero abundante. Para muchos, la mejor que habían comido en su vida.",
       ["EN TERCERA"], ["SIMPLE", "PERO BUENA"], "t083",
       "a plain long table with families eating stew and bread"),
    _e("Por las noches, abajo tocaban gaitas y violines y la gente bailaba hasta cansarse.",
       ["ABAJO"], ["SE BAILABA"], "t084",
       "immigrants dancing to a fiddle in a lower deck room"),
    _e("Arriba, una orquesta de ocho músicos tocaba mientras los pasajeros tomaban el té.",
       ["ARRIBA"], ["LA ORQUESTA"], "t085",
       "a small string band playing in an elegant lounge"),
    _e("El barco tenía su propio diario impreso a bordo, y hasta una oficina de correos con cinco empleados.",
       ["DIARIO", "PROPIO"], ["Y OFICINA", "DE CORREO"], "t086",
       "a small ship printing office and mail sorting room"),
    _e("También tenía algo nuevísimo para la época: un telégrafo Marconi que mandaba mensajes por radio.",
       ["TELEGRAFO"], ["MARCONI"], "t087",
       "two operators at a radio telegraph desk with headphones"),
    _e("Lo manejaban dos jóvenes, Yak Fílips y Járold Braid. Y no trabajaban para el barco.",
       ["PHILLIPS"], ["Y BRIDE"], "t088",
       "two young radio operators working in a small cabin"),
    _e("Trabajaban para la compañía Marconi. Su tarea principal era mandar los telegramas personales de los pasajeros ricos.",
       ["SU TRABAJO"], ["TELEGRAMAS", "DE PASAJEROS"], "t089",
       "a stack of telegram forms beside a telegraph key"),
    _e("Ese detalle, que parece administrativo, va a costar vidas en unas horas.",
       ["UN DETALLE"], ["QUE COSTARA", "VIDAS"], "t090",
       "a pile of unsent message slips spiked on a desk holder"),

    # ---------- LOS AVISOS DE HIELO ----------
    _e("Porque desde el viernes, los barcos que iban delante empezaron a mandar avisos de hielo.",
       ["LLEGAN LOS", "AVISOS"], ["HAY HIELO", "ADELANTE"], "t091",
       "a radio message slip with a warning and an iceberg drawing"),
    _e("Ese invierno había sido raro. Se habían soltado más icebergs que de costumbre y bajaron más al sur.",
       ["UN INVIERNO", "RARO"], ["MAS HIELO", "AL SUR"], "t092",
       "a map of the north atlantic with icebergs drifting south"),
    _e("El domingo catorce de abril llegaron siete avisos distintos. Siete.",
       ["7 AVISOS"], ["EN UN SOLO", "DIA"], "t093",
       "seven message slips laid out in a row on a table"),
    _e("El primero, del barco Caronia. El segundo, del Balten. El tercero, del Amérika.",
       ["CARONIA"], ["BALTIC", "Y AMERIKA"], "t094",
       "three ship names written on message forms"),
    _e("Algunos llegaron al puente. Otros quedaron traspapelados. Uno terminó en el bolsillo del dueño de la naviera.",
       ["ALGUNOS", "LLEGARON"], ["OTROS SE", "PERDIERON"], "t095",
       "a folded telegram in a suit pocket"),
    _e("Ísmey guardó un aviso de hielo en su bolsillo y se lo mostró a unas señoras como si fuera una curiosidad.",
       ["ISMAY LO", "GUARDA"], ["COMO UNA", "CURIOSIDAD"], "t096",
       "a man showing a paper to two seated ladies in a lounge"),
    _e("A la noche llegó el aviso más importante, del barco Mesaba. Describía un campo de hielo justo en la ruta.",
       ["EL MESABA"], ["UN CAMPO", "DE HIELO"], "t097",
       "a radio room with an urgent message being written down"),
    _e("Ese mensaje nunca llegó al puente. Fílips estaba tapado de telegramas personales atrasados.",
       ["NUNCA LLEGO"], ["AL PUENTE"], "t098",
       "an operator buried under a pile of telegram papers"),
    _e("A las once menos cuarto, el barco Califórnian intentó avisar: estamos detenidos, rodeados de hielo.",
       ["EL", "CALIFORNIAN"], ["DETENIDO", "POR EL HIELO"], "t099",
       "a small steamer stopped in a field of ice at night"),
    _e("El mensaje entró tan fuerte que le reventó los oídos a Fílips, que estaba trabajando con auriculares.",
       ["ENTRO", "MUY FUERTE"], ["CASI LO", "ENSORDECE"], "t100",
       "a radio operator wincing with headphones on"),
    _e("Y Fílips contestó lo que no debía: cállate, cállate, estoy ocupado con Cabo Rays.",
       ["CALLATE"], ["ESTOY", "OCUPADO"], "t101",
       "an annoyed operator tapping angrily at a telegraph key"),
    _e("El operador del Califórnian se ofendió, apagó su equipo y se fue a dormir.",
       ["EL OTRO", "OPERADOR"], ["APAGA", "Y SE VA"], "t102",
       "an operator switching off a radio set and leaving the cabin"),
    _e("Esa radio apagada, a menos de treinta kilómetros de distancia, es una de las tragedias dentro de la tragedia.",
       ["UNA RADIO", "APAGADA"], ["A 30", "KILOMETROS"], "t103",
       "a dark silent radio room with a switched off set"),
    _e("Aun así, el Titánic no bajó la velocidad. Iba a veintidós nudos y medio, casi a máxima potencia.",
       ["NO FRENA"], ["22 NUDOS"], "t104",
       "an engine telegraph dial set to full ahead"),
    _e("¿Por qué? Porque en esa época era normal. Se confiaba en ver el hielo a tiempo y esquivarlo.",
       ["ERA LO", "NORMAL"], ["VERLO", "Y ESQUIVARLO"], "t105",
       "a lookout scanning the sea with a ship bow below"),
    _e("Pero esa noche pasó algo poco frecuente: no había luna, no había viento y el mar estaba como un espejo.",
       ["SIN LUNA"], ["SIN VIENTO", "MAR ESPEJO"], "t106",
       "a perfectly flat black sea under a starry moonless sky"),
    _e("Sin olas rompiendo contra la base del hielo, los icebergs no se ven. Se pierden en el negro del agua.",
       ["SIN OLAS"], ["EL HIELO", "NO SE VE"], "t107",
       "an iceberg barely visible in flat dark water"),
    _e("Y para colmo, los vigías no tenían binoculares. Los del barco habían desaparecido antes de zarpar.",
       ["SIN", "BINOCULARES"], ["DESAPARECIERON", "EN EL PUERTO"], "t108",
       "an empty binocular case in a locked cabinet"),
    _e("Estaban guardados en un armario y la única llave se la había llevado un oficial que fue reemplazado en Sautámpton.",
       ["LA LLAVE"], ["SE LA LLEVO", "UN OFICIAL"], "t109",
       "a single key in a man's hand walking away from a ship"),

    # ---------- EL CHOQUE ----------
    _e("Once y treinta y nueve de la noche. En el puesto de vigía, Fréderick Flit mira hacia adelante.",
       ["23:39"], ["EL VIGIA", "MIRA"], "t110",
       "a lookout in a crows nest peering into darkness"),
    _e("La temperatura del aire estaba en cero grados. El agua, a menos dos.",
       ["CERO GRADOS"], ["EL AGUA", "A -2"], "t111",
       "a thermometer showing freezing beside a ship rail"),
    _e("De repente, una mancha negra crece en el horizonte. No es una nube. Es hielo.",
       ["UNA MANCHA"], ["NEGRA"], "t112",
       "a dark iceberg shape emerging from the night ahead"),
    _e("Flit toca la campana tres veces y agarra el teléfono del puente. Dice cinco palabras: iceberg, justo delante.",
       ["TRES", "CAMPANADAS"], ["ICEBERG", "AL FRENTE"], "t113",
       "a lookout ringing a bell and grabbing a telephone"),
    _e("En el puente, el primer oficial Uíliam Múrdok ordena todo a estribor y máquinas atrás.",
       ["MURDOCH"], ["TODO A", "ESTRIBOR"], "t114",
       "an officer pulling an engine telegraph lever on a bridge"),
    _e("El timón gira. El barco empieza a responder. Pero un barco de cuarenta y seis mil toneladas no gira rápido.",
       ["EL TIMON", "GIRA"], ["46 MIL", "TONELADAS"], "t115",
       "a ships wheel being turned hard by a sailor"),
    _e("Treinta y siete segundos. Ese fue todo el tiempo entre el aviso y el golpe.",
       ["37", "SEGUNDOS"], ["ESO FUE", "TODO"], "t116",
       "a pocket watch face with the second hand moving"),
    _e("Y casi lo logra. Casi. La proa pasa de largo. Pero el costado del barco raspa el hielo bajo el agua.",
       ["CASI LO", "ESQUIVA"], ["ROZA POR", "DEBAJO"], "t117",
       "a ship hull scraping past an iceberg underwater"),
    _e("Arriba casi no se sintió. Algunos pasajeros creyeron que se había caído algo en la cocina.",
       ["ARRIBA"], ["CASI NO SE", "SINTIO"], "t118",
       "passengers in a lounge barely reacting to a bump"),
    _e("Unos chicos de primera clase salieron a jugar con los pedazos de hielo que cayeron en la cubierta.",
       ["JUGABAN"], ["CON EL HIELO", "CAIDO"], "t119",
       "young men kicking chunks of ice on a ship deck"),
    _e("Abajo, en las calderas, fue otra cosa. Los fogoneros vieron entrar el agua como una pared.",
       ["ABAJO"], ["ENTRA EL AGUA"], "t120",
       "stokers running as water bursts into a boiler room"),
    _e("El hielo no abrió un tajo enorme. Abrió una serie de rendijas y juntas reventadas a lo largo del casco.",
       ["NO FUE UN", "TAJO"], ["FUERON", "RENDIJAS"], "t121",
       "a hull plate with popped rivets and thin gaps"),
    _e("La superficie total de esas aberturas era de apenas un metro cuadrado. Un metro cuadrado hundió al Titánic.",
       ["UN METRO", "CUADRADO"], ["HUNDIO AL", "TITANIC"], "t122",
       "a small square outline drawn over a giant ship hull"),
    _e("Pero estaban repartidas a lo largo de cinco compartimientos. Cinco. Y el barco aguantaba cuatro.",
       ["CINCO", "SECCIONES"], ["AGUANTABA", "CUATRO"], "t123",
       "a ship diagram with five front compartments shaded"),
    _e("Ándrius bajó a mirar, hizo la cuenta y volvió al puente con la peor noticia posible.",
       ["ANDREWS"], ["HACE LA", "CUENTA"], "t124",
       "an engineer inspecting a flooded corridor with a lamp"),
    _e("Le dijo al capitán: este barco se va a hundir. Es una certeza matemática.",
       ["SE VA A", "HUNDIR"], ["CERTEZA", "MATEMATICA"], "t125",
       "an engineer speaking gravely to a captain on the bridge"),
    _e("El capitán preguntó cuánto tiempo tenían. La respuesta fue: una hora, quizás dos.",
       ["CUANTO", "TIEMPO"], ["UNA HORA", "QUIZAS DOS"], "t126",
       "a captain looking at a clock on a bridge wall"),
    _e("Dos mil doscientas personas a bordo. Lugar en los botes para la mitad. Y menos de dos horas.",
       ["2200", "PERSONAS"], ["BOTES PARA", "LA MITAD"], "t127",
       "a crowd of figures beside a small row of lifeboats"),
]
