"""EL TITANIC — parte 3: la evacuación, el hundimiento, el rescate y el después."""

from titanic_parte1 import _e

ESCENAS = [
    # ---------- LA EVACUACIÓN ----------
    _e("Doce y cinco de la madrugada. El capitán da la orden de destapar los botes y despertar a los pasajeros.",
       ["00:05"], ["DESTAPEN", "LOS BOTES"], "t128",
       "sailors uncovering lifeboats on a night deck"),
    _e("Y acá empieza el segundo desastre: casi nadie creía que el barco se estuviera hundiendo.",
       ["NADIE", "CREIA"], ["QUE SE", "HUNDIA"], "t129",
       "passengers in dressing gowns chatting calmly in a corridor"),
    _e("La cubierta estaba helada, el barco parecía firme y adentro había luz, música y calefacción.",
       ["ADENTRO"], ["LUZ Y", "CALEFACCION"], "t130",
       "a warm lit lounge contrasted with a dark cold deck outside"),
    _e("¿Quién quiere bajar a un botecito de madera, en el medio del Atlántico, a menos dos grados?",
       ["QUIEN QUIERE"], ["BAJAR A UN", "BOTECITO"], "t131",
       "a small wooden lifeboat hanging over black water"),
    _e("A las doce y cuarto, Fílips empieza a mandar la señal de auxilio. Primero el código viejo, ce cu de.",
       ["00:15"], ["PIDEN AUXILIO"], "t132",
       "a radio operator sending distress signals urgently"),
    _e("Más tarde Braid le dice, medio en broma: manda el nuevo, el ese o ese, capaz es tu última oportunidad de usarlo.",
       ["MANDA EL", "NUEVO"], ["S O S"], "t133",
       "two operators in a radio room, one smiling grimly"),
    _e("Fue una de las primeras veces en la historia que se usó el ese o ese en un naufragio real.",
       ["UNA DE LAS", "PRIMERAS"], ["VECES EN LA", "HISTORIA"], "t134",
       "radio waves spreading from a ship antenna over the sea"),
    _e("Varios barcos contestan. Pero están lejos. El más cercano que responde es el Carpatia, a noventa y tres kilómetros.",
       ["EL CARPATHIA"], ["A 93", "KILOMETROS"], "t135",
       "a small steamer at night with a map line to a sinking ship"),
    _e("Su capitán, Ártur Róstron, hace algo increíble: apaga la calefacción del barco para darle todo el vapor a las máquinas.",
       ["ROSTRON"], ["APAGA LA", "CALEFACCION"], "t136",
       "a captain giving orders while crew work in an engine room"),
    _e("Consigue una velocidad que su barco nunca había alcanzado. Pero aun así tardará cuatro horas.",
       ["MAS RAPIDO", "QUE NUNCA"], ["AUN ASI", "4 HORAS"], "t137",
       "a small ship pushing hard through the night sea"),
    _e("Mientras tanto, en el Titánic, empiezan a bajar los botes. Y bajan casi vacíos.",
       ["BAJAN LOS", "BOTES"], ["CASI VACIOS"], "t138",
       "a half empty lifeboat being lowered down a ship side"),
    _e("El bote número siete fue el primero. Tenía lugar para sesenta y cinco personas. Bajó con veintiocho.",
       ["BOTE 7"], ["28 DE 65"], "t139",
       "a lifeboat with few people inside lowered from davits"),
    _e("El bote número uno fue el más vergonzoso: capacidad para cuarenta, bajó con doce personas.",
       ["BOTE 1"], ["12 DE 40"], "t140",
       "a nearly empty lifeboat on dark water"),
    _e("¿Por qué? Porque los oficiales tenían miedo de que los pescantes se rompieran si bajaban el bote lleno.",
       ["TENIAN MIEDO"], ["DE ROMPER", "LOS PESCANTES"], "t141",
       "davit ropes straining with a loaded lifeboat"),
    _e("Nadie les había dicho que esos botes habían sido probados llenos y aguantaban perfectamente.",
       ["Y AGUANTABAN"], ["NADIE", "LO SABIA"], "t142",
       "a test lifeboat full of sandbags hanging safely"),
    _e("Del lado de estribor, Múrdok dejaba subir hombres si no había mujeres esperando.",
       ["A ESTRIBOR"], ["SUBIAN", "HOMBRES"], "t143",
       "an officer helping men into a lifeboat"),
    _e("Del lado de babor, Láitoler interpretó la orden al pie de la letra: mujeres y niños, y nadie más.",
       ["A BABOR"], ["SOLO MUJERES", "Y NIÑOS"], "t144",
       "an officer blocking a man from entering a lifeboat"),
    _e("Por esa diferencia entre dos oficiales, tu lado del barco decidía tus chances de vivir.",
       ["TU LADO"], ["DECIDIA TU", "SUERTE"], "t145",
       "a ship deck split down the middle with people on both sides"),
    _e("Abajo, en tercera clase, la mayoría todavía no sabía nada. Y muchos no hablaban inglés.",
       ["EN TERCERA"], ["NO SABIAN", "NADA"], "t146",
       "families waiting in a lower deck corridor with luggage"),
    _e("Algunos pasillos hacia arriba estaban cerrados con rejas, por reglas de inmigración del puerto de llegada.",
       ["REJAS"], ["EN LOS", "PASILLOS"], "t147",
       "a locked gate in a ship corridor with people gathered"),
    _e("Otros simplemente se perdieron. Ese barco era un laberinto que ni la tripulación conocía del todo.",
       ["UN", "LABERINTO"], ["HASTA PARA", "LA TRIPULACION"], "t148",
       "a confusing junction of ship corridors with arrows"),
    _e("De los pasajeros de primera clase se salvó más del sesenta por ciento. De los de tercera, menos del veinticinco.",
       ["PRIMERA 60%"], ["TERCERA 25%"], "t149",
       "a simple bar chart with three columns of different heights"),
    _e("De los niños de primera clase murió uno solo. De los niños de tercera clase murieron más de cincuenta.",
       ["UN NIÑO", "EN PRIMERA"], ["MAS DE 50", "EN TERCERA"], "t150",
       "child figures drawn in two groups, one small one large"),
    _e("El hundimiento no fue solo un accidente. Fue también un retrato de cómo estaba ordenado el mundo.",
       ["NO FUE SOLO"], ["UN ACCIDENTE"], "t151",
       "a ship cross section with decks stacked like social classes"),

    # ---------- HISTORIAS ----------
    _e("Y en el medio del caos pasaron cosas que todavía cuesta creer.",
       ["EN EL CAOS"], ["PASARON", "COSAS"], "t152",
       "people helping each other on a tilting deck"),
    _e("Ísidor Straus, dueño de una gran tienda de Nueva York, tenía lugar en un bote por su edad. Lo rechazó.",
       ["STRAUS"], ["RECHAZA", "SU LUGAR"], "t153",
       "an elderly gentleman refusing a place in a lifeboat"),
    _e("Dijo que no iba a subir antes que otros hombres. Su esposa Ida se negó a dejarlo.",
       ["NO SUBIRE"], ["ANTES QUE", "OTROS"], "t154",
       "an old couple standing together at a ship rail"),
    _e("Le dio su abrigo a la mucama, se sentó con su marido en una reposera y esperaron juntos.",
       ["ELLA SE", "QUEDA"], ["ESPERAN", "JUNTOS"], "t155",
       "an elderly couple sitting side by side on deck chairs"),
    _e("Gúguenjaim, el magnate, se cambió de ropa. Se puso su mejor traje y dijo: vamos a hundirnos como caballeros.",
       ["GUGGENHEIM"], ["COMO UN", "CABALLERO"], "t156",
       "a man in evening dress standing calmly amid chaos"),
    _e("Moli Braun, la millonaria, remó en su bote y peleó a los gritos para volver a buscar sobrevivientes.",
       ["MOLLY BROWN"], ["QUIERE", "VOLVER"], "t157",
       "a woman rowing a lifeboat arguing with a crewman"),
    _e("El diseñador del barco, Tomas Ándrius, fue visto por última vez en el salón de fumar, mirando un cuadro.",
       ["ANDREWS"], ["VISTO POR", "ULTIMA VEZ"], "t158",
       "a man standing alone in a smoking room looking at a painting"),
    _e("No llevaba puesto el salvavidas. Había pasado la última hora golpeando puertas para que la gente subiera.",
       ["SIN", "SALVAVIDAS"], ["AVISO HASTA", "EL FINAL"], "t159",
       "a man knocking on cabin doors along a corridor"),
    _e("El capitán Smiz recorrió el barco repitiendo una frase: cada uno por su cuenta, hicieron su deber.",
       ["EL CAPITAN"], ["LOS LIBERA", "DE SU DEBER"], "t160",
       "a captain speaking to crew members on a sloping deck"),
    _e("Los treinta y cinco ingenieros del cuarto de máquinas se quedaron abajo hasta el último minuto.",
       ["35", "INGENIEROS"], ["SE QUEDAN", "ABAJO"], "t161",
       "engineers working among machinery in a lit engine room"),
    _e("Gracias a ellos hubo luz eléctrica casi hasta el final. Ninguno sobrevivió.",
       ["HUBO LUZ"], ["HASTA EL", "FINAL"], "t162",
       "a ship deck lit by electric bulbs at a steep angle"),
    _e("Los cinco empleados del correo intentaron salvar las bolsas de cartas. Murieron los cinco.",
       ["EL CORREO"], ["MURIERON", "LOS CINCO"], "t163",
       "men carrying mail sacks up a flooding stairway"),
    _e("Y la orquesta, dirigida por Uólas Jártli, empezó a tocar en cubierta para calmar a la gente.",
       ["LA", "ORQUESTA"], ["TOCA EN", "CUBIERTA"], "t164",
       "eight musicians playing on a tilting ship deck at night"),
    _e("Tocaron durante más de una hora, mientras el barco se inclinaba. Ninguno de los ocho sobrevivió.",
       ["MAS DE", "UNA HORA"], ["NINGUNO", "SOBREVIVIO"], "t165",
       "musicians playing while the deck tilts steeply"),

    # ---------- EL FINAL ----------
    _e("A la una y cuarenta, ya casi no quedaban botes. Y quedaban mil quinientas personas a bordo.",
       ["01:40"], ["1500 SIGUEN", "A BORDO"], "t166",
       "a crowded deck with empty davits swinging"),
    _e("Ahí recién la gente entendió. Y empezó el pánico de verdad.",
       ["AHI", "ENTENDIERON"], ["EMPIEZA EL", "PANICO"], "t167",
       "a panicked crowd pushing toward the stern"),
    _e("Los últimos botes plegables se lanzaron a las apuradas. Uno quedó dado vuelta y treinta hombres se treparon arriba.",
       ["EL BOTE", "DADO VUELTA"], ["30 HOMBRES", "ENCIMA"], "t168",
       "men standing on an overturned collapsible boat"),
    _e("A las dos y cinco, la proa ya estaba bajo el agua y la popa empezaba a levantarse.",
       ["02:05"], ["LA POPA", "SE LEVANTA"], "t169",
       "a liner with bow submerged and stern rising"),
    _e("Adentro, todo lo que no estaba atornillado se vino abajo. Pianos, vajilla, muebles, todo.",
       ["ADENTRO"], ["SE DERRUMBA", "TODO"], "t170",
       "furniture and piano sliding down a tilting room"),
    _e("A las dos y dieciocho se apagaron las luces. Y el barco quedó a oscuras, casi vertical.",
       ["02:18"], ["SE APAGAN", "LAS LUCES"], "t171",
       "a ship silhouette going dark against the stars"),
    _e("Y entonces se escuchó un ruido inmenso. El casco se partió en dos entre las chimeneas.",
       ["SE PARTE"], ["EN DOS"], "t172",
       "a ship hull breaking in half at the middle"),
    _e("Durante setenta años nadie les creyó a los sobrevivientes que contaron eso. Los ingenieros decían que era imposible.",
       ["NADIE LES", "CREYO"], ["POR 70 AÑOS"], "t173",
       "witnesses testifying before a panel of officials"),
    _e("Tenían razón los sobrevivientes. Se partió. Y hoy las dos mitades están a ochocientos metros una de la otra.",
       ["TENIAN", "RAZON"], ["DOS MITADES", "EN EL FONDO"], "t174",
       "two halves of a wreck lying apart on the seabed"),
    _e("La popa flotó unos segundos más, se levantó casi recta y se hundió girando como un tornillo.",
       ["LA POPA"], ["SE HUNDE", "GIRANDO"], "t175",
       "a ship stern standing vertical before sinking"),
    _e("Dos y veinte de la madrugada del quince de abril de mil novecientos doce. El Titánic desaparece.",
       ["02:20"], ["DESAPARECE"], "t176",
       "empty dark water with only floating debris"),
    _e("Habían pasado dos horas y cuarenta minutos desde el roce con el hielo.",
       ["2 HORAS"], ["Y 40", "MINUTOS"], "t177",
       "a clock face marking a short passage of time"),

    # ---------- EL AGUA ----------
    _e("Pero la parte más dura no fue el hundimiento. Fue lo que pasó después.",
       ["LO PEOR"], ["VINO DESPUES"], "t178",
       "hundreds of small figures floating in dark water"),
    _e("Más de mil personas quedaron en el agua, con salvavidas puestos, flotando.",
       ["MIL", "PERSONAS"], ["EN EL AGUA"], "t179",
       "people in life jackets floating in a cold sea at night"),
    _e("El agua estaba a menos dos grados. A esa temperatura el cuerpo aguanta quince o veinte minutos.",
       ["MENOS DOS", "GRADOS"], ["15 MINUTOS", "DE VIDA"], "t180",
       "a thermometer beside icy water and floating ice"),
    _e("No murieron ahogados. Murieron congelados, casi todos en menos de media hora.",
       ["NO SE", "AHOGARON"], ["MURIERON", "DE FRIO"], "t181",
       "still figures floating among ice fragments"),
    _e("Los que estaban en los botes escucharon los gritos. Sobrevivientes lo describieron como un ruido que nunca olvidaron.",
       ["LOS GRITOS"], ["NUNCA SE", "OLVIDARON"], "t182",
       "people in a lifeboat covering their ears in the dark"),
    _e("Los botes tenían lugar para casi quinientas personas más. Y casi ninguno volvió.",
       ["SOBRABA", "LUGAR"], ["CASI NADIE", "VOLVIO"], "t183",
       "half empty lifeboats floating away from a debris field"),
    _e("Tenían miedo de que la gente desesperada los diera vuelta y se hundieran todos.",
       ["TENIAN MIEDO"], ["DE VOLCAR"], "t184",
       "frightened faces in a lifeboat looking toward the water"),
    _e("Solo un bote regresó de verdad: el número catorce, con el oficial Lo, que repartió a su gente y volvió a buscar.",
       ["EL BOTE 14"], ["VOLVIO"], "t185",
       "a lifeboat rowing back toward floating survivors"),
    _e("Volvió demasiado tarde. Del agua rescataron apenas a seis personas con vida.",
       ["TARDE"], ["SOLO 6", "RESCATADOS"], "t186",
       "crew pulling a survivor from the water into a boat"),

    # ---------- EL RESCATE ----------
    _e("A las cuatro y diez de la mañana llegó el Carpatia y empezó a recoger a los sobrevivientes.",
       ["04:10"], ["LLEGA EL", "CARPATHIA"], "t187",
       "a steamer beside lifeboats at dawn taking people aboard"),
    _e("Cuando salió el sol, vieron por primera vez dónde estaban: rodeados de icebergs enormes.",
       ["AL AMANECER"], ["RODEADOS", "DE HIELO"], "t188",
       "dawn light revealing many icebergs around small boats"),
    _e("Róstron dijo después que si hubiera visto ese campo de hielo de día, jamás habría cruzado a esa velocidad.",
       ["ROSTRON"], ["NO LO HABRIA", "CRUZADO"], "t189",
       "a captain on a bridge staring at an ice field"),
    _e("Rescataron a setecientas cinco personas. Murieron mil quinientas diecisiete.",
       ["705", "SALVADOS"], ["1517", "MUERTOS"], "t190",
       "two groups of figures, one small one large, side by side"),
    _e("El Califórnian, el barco de la radio apagada, apareció recién a la mañana. Había estado cerca toda la noche.",
       ["EL", "CALIFORNIAN"], ["LLEGA A LA", "MAÑANA"], "t191",
       "a steamer arriving late at an empty sea"),
    _e("Sus tripulantes habían visto cohetes en el horizonte. Pensaron que eran fuegos artificiales de una fiesta.",
       ["VIERON", "COHETES"], ["CREYERON QUE", "ERA FIESTA"], "t192",
       "sailors watching distant flares from a ship deck"),
    _e("Nadie despertó al operador de radio. Y eso convirtió al capitán Stánli Lord en el hombre más señalado de la historia naval.",
       ["NADIE LO", "DESPERTO"], ["EL CAPITAN", "SEÑALADO"], "t193",
       "a sleeping radio operator with a silent set beside him"),
    _e("El Carpatia llegó a Nueva York el jueves a la noche, bajo la lluvia. Lo esperaban cuarenta mil personas.",
       ["NUEVA YORK"], ["40 MIL", "ESPERANDO"], "t194",
       "a huge crowd with umbrellas waiting at a rainy dock"),
    _e("Antes de bajar a la gente, Róstron mandó descargar los trece botes salvavidas del Titánic que habían recuperado.",
       ["PRIMERO"], ["LOS BOTES"], "t195",
       "lifeboats being hoisted onto a dock at night"),
    _e("Fue lo único grande que quedó del barco más grande del mundo.",
       ["FUE LO UNICO"], ["QUE QUEDO"], "t196",
       "empty wooden lifeboats lined up on a dock"),

    # ---------- CONSECUENCIAS ----------
    _e("Después vinieron dos investigaciones: una en Estados Unidos y otra en el Reino Unido.",
       ["DOS"], ["INVESTIGACIONES"], "t197",
       "an official inquiry room with a long table and witnesses"),
    _e("Ísmey, el dueño de la naviera, se había subido a un bote. Y sobrevivió.",
       ["ISMAY"], ["SOBREVIVIO"], "t198",
       "a man sitting quietly in a lifeboat among women"),
    _e("La prensa lo destrozó. Lo llamaron el cobarde del siglo y vivió el resto de su vida escondido.",
       ["LA PRENSA"], ["LO DESTROZO"], "t199",
       "newspaper headlines with an accusing portrait"),
    _e("Todavía se discute si fue un cobarde o un hombre que subió a un bote que estaba por bajar medio vacío.",
       ["TODAVIA"], ["SE DISCUTE"], "t200",
       "two sides of an argument drawn as a balance scale"),
    _e("Las investigaciones no encontraron un solo culpable. Encontraron una cadena de descuidos.",
       ["NO HUBO UN", "CULPABLE"], ["HUBO UNA", "CADENA"], "t201",
       "a chain with several links drawn across a page"),
    _e("Y de esa tragedia salieron las reglas que hoy nos protegen a todos en el mar.",
       ["DE AHI", "SALIERON"], ["LAS REGLAS", "DE HOY"], "t202",
       "a rulebook open beside a modern lifeboat"),
    _e("Botes para todos los pasajeros, sin excepción. Esa es la primera y la más importante.",
       ["BOTES"], ["PARA TODOS"], "t203",
       "a full row of lifeboats along a ship rail"),
    _e("Simulacros obligatorios de evacuación al empezar cada viaje. Por eso hoy te hacen ese ejercicio apenas subís a un crucero.",
       ["SIMULACRO"], ["OBLIGATORIO"], "t204",
       "passengers in life jackets at a muster drill"),
    _e("Radio encendida las veinticuatro horas, con guardia permanente. Nunca más una radio apagada.",
       ["RADIO"], ["24 HORAS"], "t205",
       "a manned radio room with an operator on watch"),
    _e("Y se creó la Patrulla Internacional del Hielo, que desde entonces vigila los icebergs del Atlántico norte.",
       ["PATRULLA"], ["DEL HIELO"], "t206",
       "a patrol ship and an aircraft watching icebergs"),
    _e("Desde que existe esa patrulla, ningún barco que siguió sus avisos volvió a hundirse por un iceberg.",
       ["DESDE", "ENTONCES"], ["NINGUN", "HUNDIMIENTO"], "t207",
       "a modern ship sailing safely past a marked iceberg"),

    # ---------- EL PECIO ----------
    _e("El barco quedó abajo, en la oscuridad, durante setenta y tres años. Nadie sabía exactamente dónde.",
       ["73 AÑOS"], ["PERDIDO"], "t208",
       "a dark empty seabed with faint light from above"),
    _e("En mil novecientos ochenta y cinco, Róbert Bálard lo encontró a tres mil ochocientos metros de profundidad.",
       ["1985"], ["BALLARD", "LO ENCUENTRA"], "t209",
       "a deep sea submersible approaching a shipwreck bow"),
    _e("Lo buscó siguiendo el rastro de basura y escombros que había dejado al hundirse, como si fueran migas de pan.",
       ["SIGUIO EL", "RASTRO"], ["DE ESCOMBROS"], "t210",
       "a trail of scattered debris on the seafloor"),
    _e("La primera pieza que reconocieron en la pantalla fue una caldera. Igualita a las fotos de mil novecientos doce.",
       ["UNA", "CALDERA"], ["LA PRIMERA", "SEÑAL"], "t211",
       "a round ship boiler lying on the seabed"),
    _e("La proa estaba entera y clavada en el barro. La popa, destrozada por la presión.",
       ["LA PROA", "ENTERA"], ["LA POPA", "DESTROZADA"], "t212",
       "a wreck bow half buried in mud with railings intact"),
    _e("De la madera no quedaba casi nada. Los organismos del fondo se comieron todo lo que era orgánico.",
       ["LA MADERA"], ["DESAPARECIO"], "t213",
       "bare steel decks with no wooden planks remaining"),
    _e("El casco está cubierto de unas formaciones de óxido que parecen carámbanos y que se lo van comiendo despacio.",
       ["EL OXIDO"], ["SE LO COME"], "t214",
       "rusty icicle shapes hanging from a wreck hull"),
    _e("Los cálculos dicen que en unas décadas la estructura va a colapsar del todo.",
       ["EN DECADAS"], ["VA A", "COLAPSAR"], "t215",
       "a wreck structure with parts sagging and collapsing"),
    _e("Bálard pidió que lo dejaran ahí y que se lo tratara como lo que es: un cementerio.",
       ["ES UN"], ["CEMENTERIO"], "t216",
       "a memorial plaque placed on a wreck deck"),

    # ---------- CIERRE ----------
    _e("Y queda una última pregunta: ¿por qué esta historia, entre miles de naufragios, es la que no se olvida?",
       ["POR QUE"], ["NO SE OLVIDA"], "t217",
       "a single ship silhouette remembered among many"),
    _e("Porque es una historia perfecta. Tiene orgullo, tiene lujo, tiene error humano y tiene una noche sin luna.",
       ["ORGULLO"], ["ERROR", "Y AZAR"], "t218",
       "a grand ship under a starry sky"),
    _e("Y porque cada eslabón, por separado, parecía inofensivo. Un aviso traspapelado. Una llave perdida. Un mar demasiado calmo.",
       ["CADA", "ESLABON"], ["PARECIA", "INOFENSIVO"], "t219",
       "small everyday objects, a key, a paper, a calm sea"),
    _e("Ninguno de esos detalles hundía un barco. Todos juntos, sí.",
       ["NINGUNO", "SOLO"], ["TODOS", "JUNTOS SI"], "t220",
       "many small links joining into one chain"),
    _e("El Titánic no se hundió porque el mar fuera más fuerte. Se hundió porque estábamos demasiado seguros de nosotros mismos.",
       ["NO GANO", "EL MAR"], ["GANO LA", "CONFIANZA"], "t221",
       "a proud ship reflected in still water"),
    _e("Por eso todavía lo contamos. Y por eso, cada vez que alguien dice que algo es infalible, alguien más piensa en un iceberg.",
       ["POR ESO"], ["LO SEGUIMOS", "CONTANDO"], "t222",
       "an iceberg drawn with a small ship beside it"),
    _e("Gracias por acompañarme hasta el final. Si te gustó, dejá tu comentario y nos vemos en la próxima historia.",
       ["GRACIAS"], ["HASTA LA", "PROXIMA"], "t223",
       "a closing scene of a calm ocean horizon at sunrise"),
]
