"""EL TITANIC — parte 1: el gancho, la idea, la construcción y el barco por dentro.

Reglas fijas del proyecto:
- Español neutral: nunca "vos", "che" ni modismos.
- Los nombres en inglés se escriben como suenan, para que la voz los pronuncie bien.
- Títulos cortos y fijos: nunca se acortan ni se achican al renderizar.
- Cada escena tiene su propio dibujo (key -> /mnt/documents/ref_tt/<key>.png).
"""


def _e(txt, t1, t2, key, prompt, gap=0.5):
    return dict(txt=txt, gap=gap, t1=t1, t2=t2, key=key, prompt=prompt)


ESCENAS = [
    # ---------- GANCHO ----------
    _e("Dos horas y cuarenta minutos. Ese es todo el tiempo que tardó en desaparecer el barco que no se podía hundir.",
       ["EL TITANIC"], ["LA HISTORIA COMPLETA"], "t001",
       "a huge ocean liner tilted stern up in dark water, night sky"),
    _e("Mil quinientos personas murieron esa noche. Y casi ninguna murió por el choque.",
       ["1500", "MUERTOS"], ["Y CASI NADIE", "POR EL CHOQUE"], "t002",
       "a crowd of small figures standing on a sloping deck at night, lifeboats leaving"),
    _e("Murieron por decisiones. Decisiones tomadas meses antes, en oficinas con alfombra, por gente que nunca vio un iceberg.",
       ["MURIERON POR", "DECISIONES"], ["TOMADAS EN", "UNA OFICINA"], "t003",
       "businessmen around a polished office table with a ship blueprint"),
    _e("Esta es la historia completa del Titánic: cómo se construyó, cómo se hundió y por qué todavía no lo podemos olvidar.",
       ["ESTA ES", "LA HISTORIA"], ["DE PRINCIPIO", "A FINAL"], "t004",
       "a large ocean liner drawn in profile with four funnels"),
    _e("Y empieza mucho antes del hielo. Empieza con dos empresas peleándose por los pasajeros más ricos del mundo.",
       ["EMPIEZA ANTES"], ["DEL HIELO"], "t005",
       "two rival ocean liners racing side by side across the ocean"),

    # ---------- LA IDEA ----------
    _e("Mil novecientos siete. Cruzar el Atlántico en barco era el negocio más grande de la época.",
       ["1907"], ["EL GRAN NEGOCIO"], "t006",
       "a busy passenger port with crowds boarding a steamship"),
    _e("Millones de europeos emigraban a América buscando trabajo. Y los millonarios cruzaban para hacer negocios.",
       ["MILLONES", "EMIGRABAN"], ["OTROS VIAJABAN", "POR NEGOCIOS"], "t007",
       "immigrant families with suitcases in a queue beside a ship gangway"),
    _e("Dos compañías se repartían ese océano: la Kiunard y la Uait Star Lain.",
       ["DOS RIVALES"], ["CUNARD Y", "WHITE STAR"], "t008",
       "two company flags flying over the same harbour"),
    _e("La Kiunard acababa de golpear primero con dos barcos rapidísimos: el Lusitania y el Mauritania.",
       ["CUNARD GOLPEA", "PRIMERO"], ["DOS BARCOS", "VELOCES"], "t009",
       "a fast ocean liner cutting through waves with heavy smoke trailing"),
    _e("Eran los más veloces del planeta. Cruzaban el Atlántico en menos de cinco días y se llevaban toda la prensa.",
       ["LOS MAS", "VELOCES"], ["MENOS DE", "CINCO DIAS"], "t010",
       "a newspaper front page with a speeding ship illustration"),
    _e("En la Uait Star Lain hicieron una cuenta muy simple: en velocidad ya no podían ganar.",
       ["NO PODIAN", "GANAR"], ["EN VELOCIDAD"], "t011",
       "two men studying a wall chart comparing two ships"),
    _e("Entonces cambiaron el juego. Si no podían ser los más rápidos, iban a ser los más grandes y los más lujosos.",
       ["CAMBIARON", "EL JUEGO"], ["MAS GRANDES", "Y MAS LUJOSOS"], "t012",
       "a designer sketching an enormous liner on a huge sheet of paper"),
    _e("La leyenda dice que todo se decidió en una cena, en la casa de Lord Píri, en Londres.",
       ["UNA CENA"], ["EN LONDRES"], "t013",
       "two men at a candlelit dinner table talking over a small ship model"),
    _e("De un lado, Brus Ísmey, dueño de la naviera. Del otro, Píri, el hombre que construía sus barcos.",
       ["ISMAY"], ["Y PIRRIE"], "t014",
       "two portraits facing each other, one shipowner one shipbuilder"),
    _e("Esa noche dibujaron tres hermanos gigantes: el Olímpic, el Titánic y el Britanic.",
       ["TRES", "HERMANOS"], ["OLYMPIC", "TITANIC", "BRITANNIC"], "t015",
       "three identical large liners drawn side by side in a row"),
    _e("La idea era sencilla y brutal: barcos tan grandes que viajar en otra cosa pareciera un castigo.",
       ["TAN GRANDES"], ["QUE NO HABIA", "COMPARACION"], "t016",
       "a giant liner towering over tiny buildings on the shore"),

    # ---------- CONSTRUCCIÓN ----------
    _e("Los construyeron en Belfast, en el astillero Járland and Uólf, el más grande del mundo en ese momento.",
       ["BELFAST"], ["EL MAYOR", "ASTILLERO"], "t017",
       "a vast shipyard with cranes and a half built hull"),
    _e("Tuvieron que armar una estructura de acero especial, altísima, solo para poder trabajar sobre el casco.",
       ["UNA ESTRUCTURA", "ESPECIAL"], ["SOLO PARA", "CONSTRUIRLO"], "t018",
       "a huge steel gantry frame surrounding a ship hull under construction"),
    _e("Quince mil obreros trabajaron ahí. Muchos, adolescentes. Muchos, sin ningún tipo de protección.",
       ["15 MIL", "OBREROS"], ["SIN NINGUNA", "PROTECCION"], "t019",
       "workers with flat caps climbing scaffolding on a ship hull"),
    _e("El ruido de los remaches era tan fuerte que varios quedaron sordos antes de los treinta años.",
       ["EL RUIDO"], ["LOS DEJABA", "SORDOS"], "t020",
       "riveters hammering red hot rivets into a steel plate"),
    _e("Tres millones de remaches sostenían el barco. Tres millones, colocados a mano, uno por uno.",
       ["3 MILLONES"], ["DE REMACHES", "A MANO"], "t021",
       "close view of a steel hull covered in rows of rivets"),
    _e("Ocho hombres murieron durante la construcción. En esa época se consideraba un número aceptable.",
       ["8 MUERTOS"], ["EN LA OBRA"], "t022",
       "a workers memorial board beside shipyard gates"),
    _e("El casco medía doscientos sesenta y nueve metros. Parado, sería más alto que casi cualquier edificio de la época.",
       ["269 METROS"], ["DE LARGO"], "t023",
       "a ship hull compared in height with a tall city building"),
    _e("Tenía veintinueve calderas y ciento cincuenta y nueve hornos que había que alimentar con pala, día y noche.",
       ["29 CALDERAS"], ["ALIMENTADAS", "A PALA"], "t024",
       "stokers shovelling coal into glowing furnace doors"),
    _e("Quemaba seiscientas toneladas de carbón por día. Cada día del viaje.",
       ["600 TONELADAS"], ["DE CARBON", "POR DIA"], "t025",
       "a mountain of coal beside a ship boiler room hatch"),
    _e("Sus tres hélices pesaban lo mismo que decenas de autos. La central era un bloque macizo de metal.",
       ["TRES HELICES"], ["DE ACERO", "MACIZO"], "t026",
       "three giant ship propellers with workers standing beside them for scale"),
    _e("El treinta y uno de mayo de mil novecientos once, cien mil personas fueron a ver cómo lo botaban al agua.",
       ["LA BOTADURA"], ["100 MIL", "PERSONAS"], "t027",
       "a huge crowd watching a ship hull slide into the water"),
    _e("Usaron veintitrés toneladas de grasa y jabón para que el casco se deslizara hacia el mar.",
       ["23 TONELADAS"], ["DE GRASA", "Y JABON"], "t028",
       "greased slipway rails under a moving ship hull"),
    _e("Tardó sesenta y dos segundos en entrar al agua. Y nunca lo bautizaron con champán: no era costumbre de la compañía.",
       ["62 SEGUNDOS"], ["Y SIN", "CHAMPAN"], "t029",
       "a hull entering the water with a big wave, crowd waving hats"),
    _e("Después vino casi un año más de trabajo: motores, camarotes, escaleras, cocinas, alfombras y vajilla.",
       ["UN AÑO MAS"], ["DE TRABAJO"], "t030",
       "craftsmen fitting wood panels and furniture inside a ship interior"),

    # ---------- EL BARCO POR DENTRO ----------
    _e("Cuando estuvo terminado, el Titánic no era un barco. Era un hotel de lujo que flotaba.",
       ["NO ERA", "UN BARCO"], ["ERA UN HOTEL", "FLOTANTE"], "t031",
       "an elegant hotel lobby interior inside a ship"),
    _e("Tenía piscina climatizada, baños turcos, gimnasio con caballo mecánico y hasta una cancha de squash.",
       ["PISCINA"], ["GIMNASIO", "Y SQUASH"], "t032",
       "a ship swimming pool and a gymnasium with an exercise machine"),
    _e("En el gimnasio había una bicicleta fija y un camello mecánico. Sí: un camello mecánico.",
       ["UN CAMELLO"], ["MECANICO"], "t033",
       "a passenger riding a mechanical camel exercise machine"),
    _e("La Gran Escalera era la joya del barco: roble tallado, hierro forjado y una cúpula de vidrio arriba.",
       ["LA GRAN", "ESCALERA"], ["ROBLE Y", "CRISTAL"], "t034",
       "a grand wooden staircase with a glass dome above and a clock"),
    _e("En lo alto tenía un reloj tallado con dos figuras: el Honor y la Gloria coronando al Tiempo.",
       ["EL RELOJ"], ["HONOR", "Y GLORIA"], "t035",
       "a carved wooden clock panel with two allegorical figures"),
    _e("Los camarotes de primera clase costaban lo que un obrero ganaba en varios años de trabajo.",
       ["PRIMERA", "CLASE"], ["AÑOS DE", "SALARIO"], "t036",
       "a luxurious ship cabin with brass bed and thick curtains"),
    _e("Había suites con salón privado y hasta una cubierta de paseo propia, solo para dos pasajeros.",
       ["SUITES CON", "CUBIERTA"], ["PROPIA"], "t037",
       "a private promenade deck outside a luxury cabin door"),
    _e("El comedor de primera podía sentar a más de quinientas personas al mismo tiempo.",
       ["EL COMEDOR"], ["500 PERSONAS"], "t038",
       "a huge dining saloon full of set tables and chairs"),
    _e("Segunda clase también era un lujo. Sus camarotes eran mejores que la primera clase de muchos otros barcos.",
       ["SEGUNDA", "CLASE"], ["MEJOR QUE", "OTROS BARCOS"], "t039",
       "a comfortable wood panelled cabin with two bunks and a washbasin"),
    _e("Y abajo, en tercera, viajaban los que se jugaban la vida entera por empezar de nuevo en América.",
       ["TERCERA", "CLASE"], ["EMPEZAR", "DE NUEVO"], "t040",
       "immigrant families sitting together in a simple lower deck room"),
    _e("Para ellos, el Titánic también era un salto: camas limpias, comida caliente y agua corriente.",
       ["PARA ELLOS"], ["TAMBIEN ERA", "UN LUJO"], "t041",
       "a plain clean dining table with soup bowls in a lower deck"),
    _e("Pero había un detalle. Las puertas y los pasillos separaban las clases como un laberinto.",
       ["UN DETALLE"], ["PASILLOS", "COMO LABERINTO"], "t042",
       "a maze of narrow ship corridors with closed gates"),
    _e("Esa separación, esa noche, iba a decidir quién llegaba a la cubierta y quién no.",
       ["ESA SEPARACION"], ["DECIDIRIA", "QUIEN VIVIA"], "t043",
       "a locked metal gate in a ship corridor with people behind it"),
    _e("El barco tenía dieciséis compartimientos estancos que se podían cerrar con un solo interruptor del puente.",
       ["16", "SECCIONES"], ["CIERRE", "AUTOMATICO"], "t044",
       "a diagram of a ship divided into watertight compartments"),
    _e("Podía flotar con cuatro de esos compartimientos inundados. Cuatro. Ese número es clave, recordalo.",
       ["FLOTABA CON"], ["CUATRO", "INUNDADOS"], "t045",
       "a ship cross section with four front compartments shaded in water"),
    _e("El problema es que esos muros no llegaban hasta arriba. Terminaban a pocos metros sobre la línea de flotación.",
       ["LOS MUROS"], ["NO LLEGABAN", "ARRIBA"], "t046",
       "a cutaway showing low bulkhead walls inside a ship hull"),
    _e("Era como una cubetera. Si se llenaba un hueco de más, el agua pasaba al siguiente por encima.",
       ["COMO UNA", "CUBETERA"], ["EL AGUA", "DESBORDA"], "t047",
       "an ice cube tray with water overflowing from one section to the next"),
    _e("Nadie lo pensó como un peligro. Nadie imaginó un accidente que abriera cinco compartimientos a la vez.",
       ["NADIE PENSO"], ["EN CINCO"], "t048",
       "engineers looking confidently at a ship model on a table"),

    # ---------- LOS BOTES ----------
    _e("Y ahora, la decisión que mató a más gente que el iceberg: los botes salvavidas.",
       ["LA DECISION"], ["MAS FATAL"], "t049",
       "a row of lifeboats hanging on a ship deck"),
    _e("El Titánic llevaba veinte botes. Capacidad total: mil ciento setenta y ocho personas.",
       ["20 BOTES"], ["PARA 1178"], "t050",
       "twenty small lifeboats drawn in two rows"),
    _e("A bordo iban dos mil doscientas veinticuatro. El barco podía llevar más de tres mil.",
       ["IBAN 2224"], ["ENTRABAN 3000"], "t051",
       "a crowd of people beside a small number of lifeboats"),
    _e("Y lo peor: eso era perfectamente legal. La ley pedía botes según el peso del barco, no según la gente.",
       ["ERA LEGAL"], ["LA LEY MEDIA", "EL PESO"], "t052",
       "an old law book open beside a weighing scale and a ship"),
    _e("Esa ley era de mil ochocientos noventa y cuatro, cuando los barcos grandes eran cuatro veces más chicos.",
       ["UNA LEY", "DE 1894"], ["BARCOS", "MUCHO MENORES"], "t053",
       "a small old steamship next to a giant modern liner"),
    _e("Los diseñadores habían dibujado pescantes para llevar hasta sesenta y cuatro botes.",
       ["PENSARON"], ["HASTA 64", "BOTES"], "t054",
       "a deck drawing with many davits and lifeboats along the rail"),
    _e("Los sacaron. ¿El motivo? La cubierta se veía desordenada y les quitaba paisaje a los pasajeros ricos.",
       ["LOS SACARON"], ["POR ESTETICA"], "t055",
       "a clean empty promenade deck with passengers admiring the sea"),
    _e("Además pensaban que los botes eran solo taxis: servirían para llevar gente hasta otro barco que viniera a ayudar.",
       ["LOS BOTES"], ["ERAN SOLO", "TAXIS"], "t056",
       "a lifeboat rowing between two ships on calm water"),
    _e("Esa idea funcionaba con una condición: que hubiera otro barco cerca. Esa noche no lo hubo.",
       ["FALTABA ALGO"], ["OTRO BARCO", "CERCA"], "t057",
       "an empty dark horizon seen from a ship rail at night"),
    _e("Y hubo un detalle más: nunca hicieron un simulacro completo de evacuación con los pasajeros.",
       ["SIN", "SIMULACRO"], ["NADIE SABIA", "SU BOTE"], "t058",
       "an unused lifeboat drill sign on a ship wall"),
    _e("El simulacro estaba previsto para el domingo por la mañana. El capitán lo canceló.",
       ["PREVISTO EL", "DOMINGO"], ["FUE", "CANCELADO"], "t059",
       "a ship captain crossing an item off a schedule board"),
    _e("Esa misma noche, el barco chocó contra el hielo.",
       ["ESA NOCHE"], ["LLEGO EL HIELO"], "t060",
       "a dark iceberg looming close in front of a ship bow"),
]
