/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ApiPublicReferenciasRouteImport } from './routes/api/public/referencias'
import { Route as ApiPublicReferenciasIdRouteImport } from './routes/api/public/referencias.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReferenciasRoute = ApiPublicReferenciasRouteImport.update({
  id: '/api/public/referencias',
  path: '/api/public/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReferenciasIdRoute = ApiPublicReferenciasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicReferenciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/estudio': typeof EstudioRoute
  '/api/public/referencias': typeof ApiPublicReferenciasRouteWithChildren
  '/api/public/referencias/$id': typeof ApiPublicReferenciasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/estudio': typeof EstudioRoute
  '/api/public/referencias': typeof ApiPublicReferenciasRouteWithChildren
  '/api/public/referencias/$id': typeof ApiPublicReferenciasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/estudio': typeof EstudioRoute
  '/api/public/referencias': typeof ApiPublicReferenciasRouteWithChildren
  '/api/public/referencias/$id': typeof ApiPublicReferenciasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/estudio'
    | '/api/public/referencias'
    | '/api/public/referencias/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/estudio'
    | '/api/public/referencias'
    | '/api/public/referencias/$id'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/estudio'
    | '/api/public/referencias'
    | '/api/public/referencias/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  EstudioRoute: typeof EstudioRoute
  ApiPublicReferenciasRoute: typeof ApiPublicReferenciasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/referencias': {
      id: '/api/public/referencias'
      path: '/api/public/referencias'
      fullPath: '/api/public/referencias'
      preLoaderRoute: typeof ApiPublicReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/referencias/$id': {
      id: '/api/public/referencias/$id'
      path: '/$id'
      fullPath: '/api/public/referencias/$id'
      preLoaderRoute: typeof ApiPublicReferenciasIdRouteImport
      parentRoute: typeof ApiPublicReferenciasRoute
    }
  }
}

interface ApiPublicReferenciasRouteChildren {
  ApiPublicReferenciasIdRoute: typeof ApiPublicReferenciasIdRoute
}

const ApiPublicReferenciasRouteChildren: ApiPublicReferenciasRouteChildren = {
  ApiPublicReferenciasIdRoute: ApiPublicReferenciasIdRoute,
}

const ApiPublicReferenciasRouteWithChildren =
  ApiPublicReferenciasRoute._addFileChildren(ApiPublicReferenciasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  EstudioRoute: EstudioRoute,
  ApiPublicReferenciasRoute: ApiPublicReferenciasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
